### ISSUE TITLE
Retry on what errors? (setMaxRetryAttempts)

### ISSUE THREAD

**Issue by TiloGit** [box/box-java-sdk#1100]
### Description of the Issue
https://github.com/box/box-java-sdk/blob/main/doc/configuration.md#maximum-retries
We notice the retry kicks in on 5xx errors but not on `Caused by: java.net.SocketTimeoutException: Read timed out` (we set the setReadTimeout)

What errors trigger a retry and which do not? 

### Steps to Reproduce
have a low setReadTimeout and notice that no retry is happening. 

### Expected Behavior
Retry or documented what errors trigger a retry. 

### Error Message, Including Stack Trace
here a stack trace for a timeout 
```
Caused by: com.box.sdk.BoxAPIException: Couldn't connect to the Box API due to a network error.
        at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:737)
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:436)
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:403)
        at com.box.sdk.BoxFolder.uploadFile(BoxFolder.java:580)
        at com.box.sdk.BoxFolder.uploadFile(BoxFolder.java:485)
        at com.versafile.trex.cnn.box.sdk.FailsafeBoxFolder.lambda$uploadFile$9(FailsafeBoxFolder.java:119)
        at com.versafile.trex.cnn.box.sdk.FailsafeManager.lambda$timeout$4(FailsafeManager.java:104)
        at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
        at dev.failsafe.Functions.lambda$getPromise$1(Functions.java:83)
        at dev.failsafe.Functions.lambda$null$6(Functions.java:198)
        at dev.failsafe.internal.util.DelegatingScheduler.lambda$schedule$0(DelegatingScheduler.java:141)
        ... 4 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1460)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1064)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:825)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:760)
```

### Versions Used
User-Agent: Box Java SDK v3.4.0 (Java 17.0.4)

**Comment by mwwoda** [comment]
Hi @TiloGit 

SDK retries the requests in case of 5xx status codes and 429 status code (Too many requests).
