### ISSUE TITLE
Error parsing PKCS private key with java 17

### ISSUE THREAD

**Issue by hannahzhoulucky** [box/box-java-sdk#1130]
### Description of the Issue
I have exception when run box sdk 3.8.0 in java 17 while with jdk 8 it works ok. 

### Steps to Reproduce
1. use java 17 
2. call BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig, accessTokenCache);

### Expected Behavior
get Exception for Error parsing PKCS private key for Box Developer Edition

### Error Message, Including Stack Trace
Error parsing PKCS private key for Box Developer Edition.
com.box.sdk.BoxAPIException: Error parsing PKCS private key for Box Developer Edition.
        at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:672) ~[box-java-sdk-3.8.0.jar!/:na]
        at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:607) ~[box-java-sdk-3.8.0.jar!/:na]
        at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:431) ~[box-java-sdk-3.8.0.jar!/:na]
        at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:193) ~[box-java-sdk-3.8.0.jar!/:na]
        at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:232) ~[box-java-sdk-3.8.0.jar!/:na]
        at com.mastersoft.harmony.abn.build.FileUtils.downloadFromBox(FileUtils.java:168) ~[classes!/:1.0.1-SNAPSHOT]
        at com.mastersoft.harmony.abn.NzbnIndexBuilder.run(NzbnIndexBuilder.java:59) ~[classes!/:1.0.1-SNAPSHOT]
        at com.mastersoft.harmony.abn.NzbnIndexBuilder$$FastClassBySpringCGLIB$$a12012bf.invoke(<generated>) ~[classes!/:1.0.1-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.15.jar!/:5.3.15]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.15.jar!/:5.3.15]
        at com.mastersoft.harmony.abn.NzbnIndexBuilder$$EnhancerBySpringCGLIB$$2c761d4e.run(<generated>) ~[classes!/:1.0.1-SNAPSHOT]
        at com.mastersoft.harmony.abn.BnIndexBuilder.run(BnIndexBuilder.java:47) ~[classes!/:1.0.1-SNAPSHOT]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:760) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:309) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at com.mastersoft.harmony.abn.BnIndexBuilder.main(BnIndexBuilder.java:36) ~[classes!/:1.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[loqateanz-abn-builder-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[loqateanz-abn-builder-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[loqateanz-abn-builder-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[loqateanz-abn-builder-1.0.1-SNAPSHOT.jar:1.0.1-SNAPSHOT]
Caused by: org.bouncycastle.pkcs.PKCSException: unable to read encrypted data: 1.2.840.113549.1.5.13 not available: JCE cannot authenticate the provider BC
        at org.bouncycastle.pkcs.PKCS8EncryptedPrivateKeyInfo.decryptPrivateKeyInfo(Unknown Source) ~[bcpkix-jdk15on-1.57.jar!/:1.57.0]
        at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:661) ~[box-java-sdk-3.8.0.jar!/:na]
        ... 25 common frames omitted
Caused by: org.bouncycastle.operator.OperatorCreationException: 1.2.840.113549.1.5.13 not available: JCE cannot authenticate the provider BC
        at org.bouncycastle.openssl.jcajce.JceOpenSSLPKCS8DecryptorProviderBuilder$1.get(Unknown Source) ~[bcpkix-jdk15on-1.57.jar!/:1.57.0]
        ... 27 common frames omitted
Caused by: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:131) ~[na:na]
        at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:208) ~[na:na]
        at org.bouncycastle.jcajce.util.NamedJcaJceHelper.createSecretKeyFactory(Unknown Source) ~[bcprov-jdk15on-1.57.jar!/:1.57.0]
        at org.bouncycastle.openssl.jcajce.PEMUtilities.generateSecretKeyForPKCS5Scheme2(Unknown Source) ~[bcpkix-jdk15on-1.57.jar!/:1.57.0]
        ... 28 common frames omitted
Caused by: java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[na:na]
        at java.base/java.util.zip.ZipFile.getManifestName(ZipFile.java:1057) ~[na:na]
        at java.base/java.util.zip.ZipFile$1.getManifestName(ZipFile.java:1100) ~[na:na]
        at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:461) ~[na:na]
        at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:317) ~[na:na]
        at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:260) ~[na:na]
        at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:130) ~[na:na]
        at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:190) ~[na:na]
        at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:218) ~[na:na]
        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:128) ~[na:na]
        ... 31 common frames omitted

**Comment by antusus** [comment]
Hi @hannahzhoulucky,
From the stack trace I can see that BC is not available in your setup:
`Caused by: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC`
Look for this error message and you should be able to find a solution on how to register BC in your setup.
Maybe you can register BC manually
https://github.com/bcgit/bc-java/wiki/Provider-Installation
I've added: `implementation("org.bouncycastle:bcprov-jdk15on:1.57")` to my `build.gradle` and the example is able to list BC in the list of available providers.
I'm able to run Box Java SDK on Java 17 without any problems but my setup might be different then yours.

**Comment by hannahzhoulucky** [comment]
Yes, that works. thanks Antusus
