### ISSUE TITLE
Runtime Exception while searching for a User with SDk

### ISSUE THREAD

**Issue by pbale** [box/box-java-sdk#1160]
- [ yes] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ yes] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [yes ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ yes] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Runtime exception is thrown while searching for a user. I tried the search on Postman with URL, https://api.box.com/2.0/users?filter_term=gad011&fields=id,status,login and it did returned me the successful payload. but when I use the box java SDK its failing. Any help will be greatly appreciated. If you want to see more information on this please refer to the case number #2832801 on Box SDK forums. 
Note: My application uses Spring boot Framework.

### Steps to Reproduce
1. Get oAuthCode and save token information into the database
2. Check if the token is expired by, (currentTime-lastRefresh > expired) perform BoxAPIConnection.refresh()
3. Search for the user(gad011) 
Iterables.get(
            Iterables.filter(BoxUser.getAllEnterpriseUsers(BoxAPIConnection, userId, fields), onLoginFilter), 0);
where userId = gad011, fields = id, status, created_at,modifies_at, login
4. step 3 produces RuntimeException:Null

### Expected Behavior
I am expecting to see the user information with the specified fields.

### Error Message, Including Stack Trace

63248 [http-nio-8080-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException] with root cause 
   java.lang.RuntimeException: null
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:472)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:404)
	at com.box.sdk.JsonIterator.loadNextPage(JsonIterator.java:68)
	at com.box.sdk.JsonIterator.loadNextJsonObject(JsonIterator.java:102)
	at com.box.sdk.JsonIterator.hasNext(JsonIterator.java:29)
	at com.box.sdk.BoxUserIterator.hasNext(BoxUserIterator.java:21)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:635)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.Iterators.get(Iterators.java:800)
	at com.google.common.collect.Iterables.get(Iterables.java:729)
	at edu.illinois.techservices.cloudbroker.box.BaseBoxUser.getBoxUserInfo(BaseBoxUser.java:135)
	at edu.illinois.techservices.cloudbroker.box.BoxUserServiceStatus.getUserAccountInformation(BoxUserServiceStatus.java:42)
	at edu.illinois.techservices.cloudbroker.webapi.UserResource.getResource(UserResource.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

### Versions Used
Java SDK: I tried versions from 3.7 to 3.8.1. I see the same exception at same place with all these versions.
Java: jdk 17

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by lukaszsocha2** [comment]
Hi,
thak you for submitting this issue. Can you check if the same issue occurs with the most recent Java SDK release - 4.0.1. Since v4.0.0 Box Java SDK uses new network library - OkHttp, so there is a great chance that your issue will be solved by simply upgrading to the newest version. If the problem still shows up there, let us know - we will investigate it further.
Best,
@lukaszsocha2

**Comment by pbale** [comment]
thanks @lukaszsocha2. I tried updating the SDk release to 4.0.1 and I see a different error now. 
The log trace:
229360 [http-nio-8080-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.IllegalAccessError: class com.box.sdk.BoxAPIConnection tried to access method 'void okhttp3.OkHttpClient$Builder.<init>(okhttp3.OkHttpClient)' (com.box.sdk.BoxAPIConnection and okhttp3.OkHttpClient$Builder are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @1b604f19)] with root cause 
java.lang.IllegalAccessError: class com.box.sdk.BoxAPIConnection tried to access method 'void okhttp3.OkHttpClient$Builder.<init>(okhttp3.OkHttpClient)' (com.box.sdk.BoxAPIConnection and okhttp3.OkHttpClient$Builder are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @1b604f19)
	at com.box.sdk.BoxAPIConnection.buildHttpClients(BoxAPIConnection.java:240)
	at com.box.sdk.BoxAPIConnection.<init>(BoxAPIConnection.java:166)
	at com.box.sdk.BoxAPIConnection.<init>(BoxAPIConnection.java:188)
	at com.box.sdk.BoxAPIConnection.restore(BoxAPIConnection.java:280)
	at edu.illinois.techservices.cloudbroker.box.BoxAPIConnectionSuppliers$1.get(BoxAPIConnectionSuppliers.java:68)
	at edu.illinois.techservices.cloudbroker.box.BoxAPIConnectionSuppliers$1.get(BoxAPIConnectionSuppliers.java:30)
	at edu.illinois.techservices.cloudbroker.box.BaseBoxUser.checkAPIConnection(BaseBoxUser.java:76)
	at edu.illinois.techservices.cloudbroker.box.BoxUserServiceStatus.getUserAccountInformation(BoxUserServiceStatus.java:38)
	at edu.illinois.techservices.cloudbroker.webapi.UserResource.getResource(UserResource.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

**Comment by pbale** [comment]
Hello @lukaszsocha2, I had to bump my spring boot version to the most recent and that solved the issue with  java.lang.IllegalAccessError but I am back to the same RuntimeException. Its complaining at line no.418 on com.box.sdk.BoxAPIRequest.send(). I am passing BoxAPiConnection object with these values.

BoxOauth2State{
id=71565, 
accessToken=YC9AbdcsPLmPWXxuyDcHPzhtJMLa62L7, refreshToken=u23BZFyZZvMbMYy3FNEo35lAgGuBeZzLxTWSvWkQHFygcQZItlC0b78RvBvSWXBZ, lastRefresh=1681836967283, 
expires=3786000, 
userAgent=Box Java SDK v4.0.1 (Java 11.0.10), 
tokenURL=https://api.box.com/oauth2/token, 
baseURL=https://api.box.com/2.0/, 
baseUploadURL=https://upload.box.com/api/2.0/, 
revokeURL=https://api.box.com/oauth2/revoke, 
autoRefresh=true, 
maxRetrytAttempts=5}

log Trace:
56770 [http-nio-8080-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException] with root cause 
java.lang.RuntimeException: null
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:418)
	at com.box.sdk.BoxJSONRequest.send(BoxJSONRequest.java:106)
	at com.box.sdk.BoxJSONRequest.send(BoxJSONRequest.java:17)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:350)
	at com.box.sdk.BoxJSONRequest.send(BoxJSONRequest.java:101)
	at com.box.sdk.JsonIterator.loadNextPage(JsonIterator.java:68)
	at com.box.sdk.JsonIterator.loadNextJsonObject(JsonIterator.java:103)
	at com.box.sdk.JsonIterator.hasNext(JsonIterator.java:29)
	at com.box.sdk.BoxUserIterator.hasNext(BoxUserIterator.java:21)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:635)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.Iterators.get(Iterators.java:800)
	at com.google.common.collect.Iterables.get(Iterables.java:729)
	at edu.illinois.techservices.cloudbroker.box.BaseBoxUser.getBoxUserInfo(BaseBoxUser.java:135)
	at edu.illinois.techservices.cloudbroker.box.BoxUserServiceStatus.getUserAccountInformation(BoxUserServiceStatus.java:42)
	at edu.illinois.techservices.cloudbroker.webapi.UserResource.getResource(UserResource.java:246)

**Comment by lukaszsocha2** [comment]
Hi @pbale ,
does the same error show up for all calls or just `BoxUser.getAllEnterpriseUsers(...)` ? Can you try to execute, e.g. `BoxUser.Info userInfo = BoxUser.getCurrentUser(api).getInfo();` and see if the same exception is thrown.
If no exception is thrown, can you try to use [Developer Token](https://developer.box.com/guides/authentication/tokens/developer-tokens/) as an authentication method and verify if your example works. This could help us narrow down possible causes of this issue.
Best,
@lukaszsocha2

**Comment by pbale** [comment]
Hey @lukaszsocha2 ,
I drilled down to the code and found an issue with getting maxRetryAttempts setting to -1 after the restore call. 

api = BoxAPIConnection.restore(clientId, clientSecret, state);
The restore has returned the below api object:

api.getAccessToken: xxxx
api.getRefreshToken: xxxx
**api.getMaxRetryAttempts: -1**
api.getBaseUploadURL: https://upload.box.com/api/2.0/
api.getTokenURL: https://api.box.com/oauth2/token
api.getLastRefresh: 1681963701434
api.getExpires: 3963000
api.getConnectTimeout: 0

So I tried setting the maxRetryAttempts value to 5 before making the getAllEnterpriseUsers call and it has successfully searched the user and returned the information. Now the question is why the restore returning the maxRetryAttempts to -1. Is there something that you can fix on your end? 

Thanks
pbale

**Comment by lukaszsocha2** [comment]
Hi @pbale,
I noticed that you have in your state object error in key: `maxRetrytAttempts` instead of `maxRetryAttempts`. So when restoring a session, it cannot find `maxRetryAttempts` key and it fallbacks to -1 value. This could be improved on our end to use the default value (5) if `maxRetryAttempts` key is not found. We will fix it soon.
Best,
@lukaszsocha2

**Comment by pbale** [comment]
Thank you @lukaszsocha2 for fixing this.

**Comment by pbale** [comment]
upgraded to 4.1.0 and is working as expected. Thank you @lukaszsocha2 for looking into this. I appreciate the help.

Thanks,
Pbale
