### ISSUE TITLE
ClassCastException when using BoxFolder.uploadLargeFile()

### ISSUE THREAD

**Issue by AkihiroAsami** [box/box-java-sdk#1173]
### Description of the Issue
When executing chunk upload by using BoxFolder.upload LargeFile(),
ClassCastException is raised often like the error stack as the following. 
This “often” means that sometimes the process completes successfully, sometimes I get this error.

### Cause of the bug
Please see [this file](https://cloud.box.com/s/x3tk9akir6f6cp0abnq7dzhvr0rwwjuz).

### Error Message, Including Stack Trace
Exception in thread "main" com.box.sdk.BoxAPIException: Unable to commit the upload session
at com.box.sdk.LargeFileUpload.uploadHelper(LargeFileUpload.java:204)
at com.box.sdk.LargeFileUpload.upload(LargeFileUpload.java:119)
at com.box.sdk.BoxFolder.uploadLargeFile(BoxFolder.java:1189)
at boxapp.UploadLargeTest2.main(UploadLargeTest2.java:28)
Caused by: java.lang.ClassCastException: class com.box.sdk.BoxAPIResponse cannot be cast to class com.box.sdk.BoxJSONResponse (com.box.sdk.BoxAPIResponse and com.box.sdk.BoxJSONResponse are in unnamed module of loader 'app')
at com.box.sdk.BoxJSONRequest.send(BoxJSONRequest.java:106)
at com.box.sdk.BoxJSONRequest.send(BoxJSONRequest.java:17)
at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:347)
at com.box.sdk.BoxJSONRequest.send(BoxJSONRequest.java:101)
at com.box.sdk.BoxFileUploadSession.commit(BoxFileUploadSession.java:192)
at com.box.sdk.LargeFileUpload.uploadHelper(LargeFileUpload.java:201)
... 3 more

### Versions Used
Java SDK:4.1.1

**Comment by mhagmajer** [comment]
Hello @AkihiroAsami! Thanks for posting the issue, providing a really good description and also a fix suggestion. I created a PR and once it's reviewed, we'll include it in the next release.

**Comment by AkihiroAsami** [comment]
Hi @mhagmajer , I really appreciate your quick reply. And I'm glad to hear that this fix will be included in the next release ! Thank you.
