### ISSUE TITLE
Cannot parse Private Key generated for JWT (javax.crypto.BadPaddingException: pad block corrupted)

### ISSUE THREAD

**Issue by gaurav-bagga** [box/box-java-sdk#1217]
- [x ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I have generated public private key pair in developer console and downloaded it as JSON file named 0_<key_id>_config.json.
I am trying to create an instance to access the API using sdk, for this it has to parse private key inside the config json which also includes the password. I haven't edited the file it is as downloaded on creation of key pair.

The sdk API fails to read this key file.

`var api = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(config);`

The above call fails with exception.

### Steps to Reproduce
I am attaching the maven project that I am trying out. 

[com.box.test.zip](https://github.com/box/box-java-sdk/files/13687718/com.box.test.zip)

I tried decrypting the key using openssl on mac os x and it goes fine. 

`openssl pkcs8 -in key.enc`

It prompts for password on entering the password in config.json it prints the private key.
I have no idea what is happening here, the control goes to bouncy castle and something fails there.
I'll appreciate if some clue or input on the matter is provided, have I done something wrong while creating app in developer console. 

It is working with open ssl but failing in Java side, not sure what is happening.

### Expected Behavior
Should create instance and let explore the box via sdk.

### Error Message, Including Stack Trace
```
Exception in thread "main" com.box.sdk.BoxAPIException: Error parsing PKCS private key for Box Developer Edition.
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:568)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:503)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:327)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:182)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:216)
	at com.box.test.Main.main(Main.java:40)
Caused by: org.bouncycastle.pkcs.PKCSException: unable to read encrypted data: javax.crypto.BadPaddingException: pad block corrupted
	at org.bouncycastle.pkcs.PKCS8EncryptedPrivateKeyInfo.decryptPrivateKeyInfo(Unknown Source)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:557)
	... 5 more
Caused by: java.io.IOException: javax.crypto.BadPaddingException: pad block corrupted
	at java.base/javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:128)
	at java.base/javax.crypto.CipherInputStream.read(CipherInputStream.java:242)
	at org.bouncycastle.util.io.Streams.pipeAll(Unknown Source)
	at org.bouncycastle.util.io.Streams.readAll(Unknown Source)
	... 7 more
Caused by: javax.crypto.BadPaddingException: pad block corrupted
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2085)
	at java.base/javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:125)
	... 10 more
```

### Versions Used
Java SDK: 4.6.1
Java: 11

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by lukaszsocha2** [comment]
Hi @gaurav-bagga,
we are aware of this issue and are in the proces of fixing it. The temporary workaround is to override Bouncy castle version as described here: https://github.com/box/box-java-sdk?tab=readme-ov-file#fips-140-2-compliance. Sorry for inconvenience.
Best,
@lukaszsocha2

**Comment by gaurav-bagga** [comment]
@lukaszsocha2 thanks for the response and link, I will proceed with the workaround for now.

**Comment by lukaszsocha2** [comment]
Hi @gaurav-bagga,
the new release v4.7.0 with the fix is now available.
Best,
@lukaszsocha2
