### ISSUE TITLE
BoxCollaboration.updateInfo() com.box.sdk.BoxAPIResponse cannot be cast to com.box.sdk.BoxJSONResponse

### ISSUE THREAD

**Issue by luyseyal** [box/box-java-sdk#147]
#### Workflow the code is doing
1. Creates a new folder
2. Adds a collaboration to a user passed in on the command line
3. Sets the role for the user to owner
4. Calls BoxCollaboration.updateInfo() with the updated role... causing the exception below

#### Exception happening on the last line
```
BoxCollaboration.Info newCollaborationInfo = folder.collaborate(userName, BoxCollaboration.Role.EDITOR)

newCollaborationInfo.setRole(BoxCollaboration.Role.OWNER)

BoxCollaboration bc = newCollaborationInfo.getResource()
bc.updateInfo(newCollaborationInfo)
```

#### Exception
```
Exception in thread "main" java.lang.ClassCastException: com.box.sdk.BoxAPIResponse cannot be cast to com.box.sdk.BoxJSONResponse
        at com.box.sdk.BoxCollaboration.updateInfo(BoxCollaboration.java:84)
        at com.box.sdk.BoxCollaboration$updateInfo.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
        at PrintToBoxHome.setupCollaboration(PrintToBoxHome.groovy:195)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:148)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:99)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:191)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:219)
        at PrintToBoxHome.main(PrintToBoxHome.groovy:60)
```

**Comment by luyseyal** [comment]
I have gotten the project open sourced. You can see the workflow here starting on line 438 in the `setupCollaboration()` method. The actual error occurs on lines 482, 495, and 521.

I think that when you give away ownership of a collaborated folder, the returned object has a different Class. (Or I need to code this differently! :)

https://github.com/StEdwardsTeam/PrintToBox/blob/master/src/main/groovy/PrintToBox.groovy
