### ISSUE TITLE
Error parsing private key for Box Developer Edition.

### ISSUE THREAD

**Issue by majoely** [box/box-java-sdk#168]
I am getting the error above when testing the CreateAppUser.java code. 

I have downloaded both the pre-compiled jar from oss.sonatype.org and I have downloaded the source and compiled it and the error appears in both.

I followed the instructions for generation the public/private key pair and it looks fine.

When I googled parts of the stack trace "PBKDF-OpenSSL" it was suggesting that I should be searching for "PBKDF2-OpenSSL" but from what I could see that was part of the bouncycastle code.

I have been looking into this on and off for a couple of days now and have run out of options. Is this the right place to be bringing this up?

Here is the stacktrace:
>Exception in thread "main" com.box.sdk.BoxAPIException: Error parsing private key for Box Developer Edition.
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:271)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:219)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:162)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:118)
	at boxapitest.AccessAsAppUser.main(AccessAsAppUser.java:50)
Caused by: org.bouncycastle.openssl.PEMException: Unable to create OpenSSL PBDKF: PBKDF-OpenSSL SecretKeyFactory not available
	at org.bouncycastle.openssl.jcajce.PEMUtilities.getKey(Unknown Source)
	at org.bouncycastle.openssl.jcajce.PEMUtilities.getKey(Unknown Source)
	at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
	at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:265)
	... 4 more
Caused by: java.security.NoSuchAlgorithmException: PBKDF-OpenSSL SecretKeyFactory not available
	at javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:122)
	at javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:160)
	at org.bouncycastle.jcajce.util.DefaultJcaJceHelper.createSecretKeyFactory(Unknown Source)
	... 10 more
Java Result: 1

**Comment by luyseyal** [comment]
@bgoldman might have a clue

**Comment by dwilcoxen** [comment]
Same problem here on attempting to get a BoxDeveloperEditionAPIConnection: 

Unable to create OpenSSL PBDKF: PBKDF-OpenSSL SecretKeyFactory not available

**Comment by dwilcoxen** [comment]
I was using the 1.53 versions (latest at the moment) of the BouncyCastle jars. When I switched to the prior version (1.52) this error disappeared.

**Comment by majoely** [comment]
I was using 1.53 as well, changed to 1.52 and error went away.

**Comment by cheyrico2** [comment]
@majoely or @dwilcoxen ,How do you change the version? Are you using Maven?

**Comment by dwilcoxen** [comment]
I'm not using Maven, just a library of jar files that I downloaded.

**Comment by MonkeyLeeT** [comment]
Can we know why this is broken in 1.53+ and if it's to be fixed?

There must be others who need new features/fixes in 1.53+ yet need 1.52 to avoid this issue.

**Comment by bcgit** [comment]
The stack trace indicates the JcePEMDecryptorProviderBuilder has not been configured to use the BC provider.
