### ISSUE TITLE
java.lang.NumberFormatException when getting enterprise events

### ISSUE THREAD

**Issue by danielandefors** [box/box-java-sdk#185]
I'm currently unable to get enterprise events with the `EventLog` class. The error occurs because the code is trying to parse `next_stream_position` as a `long`. But the Box Content API returns a string (of the format `<integer>;<uuid>`) instead of an integer. 

```
java.lang.NumberFormatException: For input string: "1451002006632;4bdb8971-089a-4886-905e-0fdf1cce03d8"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:441)
	at java.lang.Long.parseLong(Long.java:483)
	at com.box.sdk.EventLog.<init>(EventLog.java:38)
	at com.box.sdk.EventLog.getEnterpriseEvents(EventLog.java:102)
	at com.box.sdk.EventLog.getEnterpriseEvents(EventLog.java:57)
```

**Comment by gcurtis** [comment]
Thanks for the bug report. This appears to be a breaking change made on the API side of things. If it is, we'll need add a bug fix along with a major version bump to the SDK.
