### ISSUE TITLE
what java version does box-java-sdk 2.0.0 supports?

### ISSUE THREAD

**Issue by cheyrico2** [box/box-java-sdk#207]
The content API page make no mention of the Java JDK version this SDK is compatible with? Can you please provide the recommended java version for this SDK?

**Comment by gcurtis** [comment]
It's compatible with Java 6 or higher.

**Comment by cheyrico2** [comment]
@gcurtis FYI, jose4j-0.4.4.jar requires Java 7

**Comment by cburnette** [comment]
ah, the person that added that dependency didn’t consider that.  I’ll take a look and see if there’s a version of jose4j that works with Java 6 (or send me a link if you’ve already found it)

**Comment by gcurtis** [comment]
Thanks for looking into that @cburnette.

I'm hoping that we can remove some of the App Users dependencies in the future. They seem very heavyweight and we're only using a small part of them.

**Comment by cheyrico2** [comment]
Sorry I'haven't found one yet. I'm having trouble changing the the SDK dependencies on my pc to resolve 
`Exception in thread "main" com.box.sdk.BoxAPIException: Error parsing private key for Box Developer Edition.
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:271)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:219)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:162)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(BoxDeveloperEditionAPIConnection.java:137)
	at com.ricoh.box.App.main(App.java:87)
Caused by: org.bouncycastle.openssl.EncryptionException: exception using cipher - please check password and data.
	at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
	at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:265)
	... 4 more
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1024)
	at javax.crypto.Cipher.implInit(Cipher.java:790)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:849)
	at javax.crypto.Cipher.init(Cipher.java:1348)
	at javax.crypto.Cipher.init(Cipher.java:1282)`

**Comment by cburnette** [comment]
It looks like you need to follow the instructions in the readme for installing the prior JCE library to support 256 bit keys.

**Comment by cheyrico2** [comment]
Thank you that resolve the issue
