### ISSUE TITLE
Error parsing private key for Box Developer Edition.

### ISSUE THREAD

**Issue by cheyrico2** [box/box-java-sdk#210]
I'm using box-java-sdk-2.0.0 and when I try to execute the following line from CreateAppUser.java example:

`BoxDeveloperEditionAPIConnection api = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(USER_NAME, CLIENT_ID, CLIENT_SECRET, encryptionPref)`

i get the following exception:

`Exception in thread "main" com.box.sdk.BoxAPIException: Error parsing private key for Box Developer Edition.
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:271)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:219)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:162)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:118)
	at com.ricoh.box.App.main(App.java:87)
Caused by: org.bouncycastle.openssl.EncryptionException: exception using cipher - please check password and data.
	at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
	at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:265)
	... 4 more
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1024)
	at javax.crypto.Cipher.implInit(Cipher.java:790)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:849)
	at javax.crypto.Cipher.init(Cipher.java:1348)
	at javax.crypto.Cipher.init(Cipher.java:1282)
	... 8 more`

I've verified my private key password works my key by executing the following on cywing

`openssl rsa -check -in private_key.pem`

**Comment by cheyrico2** [comment]
After reading the read me file and adding Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 7 to my project the was resolved

**Comment by janvidpa** [comment]
@cheyrico2  I have the same issue. How did you add JCE to your project could you please elaborate on it

**Comment by cheyrico2** [comment]
@janvidpa the following link that was on Box read me page will guide you. FYI, this is for JDK 7.
[Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 7](http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html)

**Comment by janvidpa** [comment]
I am using the dependency as maven, it shouldn't have caused errors then right?
Also, my project is in jdk8

**Comment by cheyrico2** [comment]
@janvidpa it probably wouldn't be a bad idea matching the JDK (http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) or changing your Execution Environment.
