### ISSUE TITLE
Box Write Error

### ISSUE THREAD

**Issue by Syed-SnapLogic** [box/box-java-sdk#211]
I am trying to write a file to my box account.  Getting the following stack trace:
Caused by: java.lang.ClassCastException: com.box.sdk.BoxAPIResponse cannot be cast to com.box.sdk.BoxJSONResponse
  at com.box.sdk.BoxFolder.uploadFile(BoxFolder.java:369)
  at com.box.sdk.BoxFolder.uploadFile(BoxFolder.java:323)
  at com.snaplogic.snaps.box.BoxWrite.process(BoxWrite.java:163)

Any guess whats happening?  Below is the code I have used.
String fileName = "somefile.txt";
            try (InputStream in = Channels.newInputStream(readChannel)) {
                // uploading
                BoxFile.Info uploadedFileNewInfo = parentFolder.uploadFile(in,
                        fileName);
            }

**Comment by Syed-SnapLogic** [comment]
@gcurtis , any answer to the above question please?
