### ISSUE TITLE
Authentication using Json Web Tokens and BoxDeveloperEditionAPIConnection always fail

### ISSUE THREAD

**Issue by zzoi** [box/box-java-sdk#286]
I'm getting this exception using JWT. I double check my private key and public key and both are correct. What I'm missing here?
Exception in thread "main" com.box.sdk.BoxAPIException: The API returned an error code: 400.

Here is my code:
JWTEncryptionPreferences encryptionPref = new JWTEncryptionPreferences();
         encryptionPref.setPublicKeyID(PUBLIC_KEY_ID);
         encryptionPref.setPrivateKey(privateKey);
         encryptionPref.setPrivateKeyPassword(PRIVATE_KEY_PASSWORD);
         encryptionPref.setEncryptionAlgorithm(EncryptionAlgorithm.RSA_SHA_256);

```
     IAccessTokenCache accessTokenCache = new     InMemoryLRUAccessTokenCache(MAX_CACHE_ENTRIES);

     BoxDeveloperEditionAPIConnection api = BoxDeveloperEditionAPIConnection.getAppUserConnection(USER_ID, 
         CLIENT_ID, CLIENT_SECRET, encryptionPref, accessTokenCache);
```

**Comment by zzoi** [comment]
This is the real issue: "Cannot obtain token based on the enterprise configuration for your app". What is the correct configuration to get access with JWT?

**Comment by dmaynard** [comment]
First it is important to know that to use the JWT grant you must get your application authorized by your enterprise admin. Your admin can authorize your app by navigating to the Enterprise Settings >> Apps >> Custom Applications and choosing to authorize a new app.    Permissions for your app will be checked against what has been authorized by your enterprise admin. This means when you make changes to the scopes or settings on your app you will need to have the app re-authorized by your admin.

**Comment by zzoi** [comment]
It's possible to get the JWT grant using my own account, I provide the authorization for my app and I also generate the public and private key with ssl.

Is there any reference or example on how to get the access token using Box SDK and the jose4j library?
This is what I'm creating until now:
Header:
{
  "kid": "My_public_key_ID",
  "alg": "RS256",
  "typ": "JWT"
}
Payload:
{
  "iss": "MY_CLIENT_ID",
  "sub": "MY_USER_ID",
  "box_sub_type": "user",
  "aud": "https://api.box.com/oauth2/token",
  "jti": "UNIQUE_ID",
  "exp": 1470775805,
  "iat": 1470774605,
  "nbf": 1470774485
}

Now I'm getting this error:
{"error":"invalid_grant","error_description":"Please check the 'exp' claim."}



Java:
  JwtClaims claims = new JwtClaims();
       
        claims.setIssuer(CLIENT_ID);
        claims.setSubject(USER_ID);
        claims.setClaim("box_sub_type", "user");
        claims.setClaim("iss", CLIENT_ID);
        claims.setClaim("sub", USER_ID);
        claims.setClaim("aud", BOX_AUDIENCE);
        claims.setClaim("jti", PUBLIC_KEY_ID + "1234567890123456");
        claims.setAudience(BOX_AUDIENCE);
        claims.setJwtId(PUBLIC_KEY_ID +  "1234567890123456");
        Date currentDate = new Date( System.currentTimeMillis() + 60000L);
        long unixTime = currentDate.getTime() / 1000;
        System.out.println(unixTime);
        claims.setClaim("exp", unixTime);
        claims.setExpirationTimeMinutesInTheFuture(20.0f);
claims.setIssuedAtToNow();  // when the token was issued/created (now)
        claims.setNotBeforeMinutesInThePast(2); // time before which the token is not yet valid (2 minutes ago)

JsonWebSignature jws = new JsonWebSignature();
        jws.setPayload(claims.toJson());

jws.setKey(pk); //Send the Private Key as an PrivateKey Object

jws.setKeyIdHeaderValue(PUBLIC_KEY_ID);
        jws.setAlgorithmHeaderValue(AlgorithmIdentifiers.RSA_USING_SHA256);

jws.setHeader("alg", "RS256");
        jws.setHeader("typ", "JWT");
        jws.setHeader("kid", PUBLIC_KEY_ID);


assertion = jws.getCompactSerialization();

**Comment by dmaynard** [comment]
There is a java server sample application that uses JWT:
See:  https://github.com/box/box-java-sdk-samples

Also see https://docs.box.com/docs/configuring-box-platform  which describes the steps necessary to configure an application to use app-users and JWT.

Also if the issues is due to clock drift from network standard time the following post may help:

https://community.box.com/t5/Developer-Forum/Current-date-time-MUST-be-before-the-expiration-date-time-listed/td-p/17871

**Comment by zzoi** [comment]
I was trying to follow the sample application that uses JWT but in that sample the token was created previously because they are using a Token already stored in the cache, that's why I need the first step of creation of the token and putting it on the cache and then access the Box API's for files management.

**Comment by zzoi** [comment]
I was able to create the JWT but I want to make sure one thing, the SDK doesn't have the JCE embedded right? we need to add it to the environment as part to the configuration of the project.
Also I have to add as a maven dependency two things plust the box-java-sdk: 
1. slf4j-api
2. slf4j-simple

Here is the link to the jar files that I have to overwrite under the security folder of my sdk.
http://www.oracle.com/technetwork/java/embedded/embedded-se/downloads/jce-7-download-432124.html

*This jar files are for the 256bit AES requirement,  the sdk 1.7 only support 128bit.
(Two more tricky parts, how to read the private key of your app and the unix time for the expiration of you JWT).

My solution:

private static String constructJWTAssertion() throws InvalidKeySpecException, NoSuchAlgorithmException, NoSuchProviderException, IOException {
		KeyPair kp = null;
		PrivateKey pk = null;
		String assertion = "";
		
		Security.addProvider(new BouncyCastleProvider());
		PemReader pemReader = new PemReader(new InputStreamReader(new FileInputStream(PRIVATE_KEY_FILE)));
		File privateKeyFile = new File(PRIVATE_KEY_FILE); // private key file in PEM format
		PEMParser pemParser = new PEMParser(new FileReader(privateKeyFile));
		Object object = pemParser.readObject();
		 
		PEMDecryptorProvider decProv = new    JcePEMDecryptorProviderBuilder().build(PRIVATE_KEY_PASSWORD.toCharArray());
		JcaPEMKeyConverter converter = new JcaPEMKeyConverter().setProvider("BC");
		 
		if (object instanceof PEMEncryptedKeyPair) {
			kp = converter.getKeyPair(((PEMEncryptedKeyPair) object).decryptKeyPair(decProv));
		}
		
		pk = kp.getPrivate();
		JwtClaims claims = new JwtClaims();
		   
	    claims.setIssuer(CLIENT_ID);
	    claims.setSubject(USER_ID);
	    claims.setClaim("box_sub_type", "enterprise");
		claims.setClaim("iss", CLIENT_ID);
		claims.setClaim("sub", ENTERPRISE_ID);
		claims.setClaim("aud", BOX_AUDIENCE);
		claims.setClaim("jti", JWT_ID); //must be between 16 and 128 characters
		claims.setAudience(BOX_AUDIENCE);
		claims.setJwtId(JWT_ID);
	
		Date currentDate = new Date( System.currentTimeMillis() + 60000L);
		long unixTime = currentDate.getTime() / 1000;
	
		claims.setClaim("exp", unixTime);
		claims.setExpirationTimeMinutesInTheFuture(1.0f);
		 
		    
		claims.setIssuedAtToNow();  // when the token was issued/created (now)
		claims.setNotBeforeMinutesInThePast(2); // time before which the token is not yet valid (2 minutes ago)
		
		JsonWebSignature jws = new JsonWebSignature();
		jws.setPayload(claims.toJson());
		jws.setKey(pk); //Send the Private Key as an PrivateKey Object 
		jws.setKeyIdHeaderValue(PUBLIC_KEY_ID);
		jws.setAlgorithmHeaderValue(AlgorithmIdentifiers.RSA_USING_SHA256);    
		jws.setHeader("alg", "RS256");
		jws.setHeader("typ", "JWT");
		jws.setHeader("kid", PUBLIC_KEY_ID);
		
		try {
		    assertion = jws.getCompactSerialization();
		} catch (JoseException e) {
		    throw new BoxAPIException("Error serializing JSON Web Token assertion.", e);
		}
		finally {
			pemReader.close();
			pemParser.close();
		}
		
		return assertion;
    }

**Comment by dmaynard** [comment]
Yes that is correct the  SDK does not have the JCE embedded.   This is not a Box thing, this is a U.S. Government requirement concerning strong encryption.

**Comment by cburnette** [comment]
The SDK already constructs the JWT assertion for you. You should not be implementing this yourself. Please see the example application mentioned for the correct way to use the SDK.

**Comment by zzoi** [comment]
Following the sample mentioned I got and error,  I changed the config.properties with the same information that I used previously and the same private_key.pem file.
 
java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)

**Comment by zzoi** [comment]
Here is more complete trace log:

Caused by: org.bouncycastle.openssl.EncryptionException: exception using cipher - please check password and data.
	at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
	at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:373)
	... 28 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:966)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:824)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:436)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	... 32 more
[WARNING] /login
com.box.sdk.BoxAPIException: Error parsing private key for Box Developer Edition.
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:379)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:327)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:237)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:305)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:169)
	at com.helpers.BoxHelper.adminClient(BoxHelper.java:67)
	at com.box.sdk.appusersexample.LoginServlet.doGet(LoginServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.bouncycastle.openssl.EncryptionException: exception using cipher - please check password and data.
	at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
	at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:373)
	... 28 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:966)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:824)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:436)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	... 32 more

**Comment by dmaynard** [comment]
Your private_key.pem file  also has to replace the private_key.pem.example in the root directory so that the application can use it to sign the JWT requests.

If this doesn't fix the problem then it may be caused by not having the JCE installed in the java SDK you are using. see:

http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html
or
http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by mekhatri1** [comment]
seems you are not using correct private key password. Please retry again
