### ISSUE TITLE
I am getting the error above when testing the CreateAppUser.java code

### ISSUE THREAD

**Issue by mekhatri1** [box/box-java-sdk#287]
I am getting the error above when testing the CreateAppUser.java code.

I am using box-java-sdk-2.1.1.jar in my code. 
I followed the instructions for generation the public/private key pair and it looks fine. 
I have added public key on box and giving correct path of private key from my dev machine. 
Also I am not using any password for private key.

Note: I have downloaded and added the required  JCE jars in my SDK ( http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) 

Exception in thread "main" com.box.sdk.BoxAPIException: Error parsing private key for Box Developer Edition.
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:379)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:327)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:237)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:305)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:169)
	at com.wellmanage.revport.portal.bo.CreateAppUser.main(CreateAppUser.java:47)
Caused by: org.bouncycastle.openssl.EncryptionException: exception using cipher - please check password and data.
	at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
	at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:373)
	... 5 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:966)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:824)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:436)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	... 9 more

**Comment by kernelogic** [comment]
Wrong private key password?

**Comment by mekhatri1** [comment]
Yes, I was putting wrong private key

**Comment by dmaynard** [comment]
@mekhatri1 I am glad you got this working.   Thank you @kernelogic  .   Closing this for now.
