### ISSUE TITLE
Box Api Returning 403 

### ISSUE THREAD

**Issue by adilakshmis** [box/box-java-sdk#290]
We accessing content api from past 5 months using Jwt, Suddenly we are getting the following exception

:04:02:851 IST] 00000610 SystemErr     R com.box.sdk.BoxAPIException: The API returned an error code: 403
[9/6/16 13:04:02:852 IST] 00000610 SystemErr     R  at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:69)
[9/6/16 13:04:02:852 IST] 00000610 SystemErr     R  at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:30)
[9/6/16 13:04:02:852 IST] 00000610 SystemErr     R  at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:423)
[9/6/16 13:04:02:852 IST] 00000610 SystemErr     R  at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:209)
[9/6/16 13:04:02:852 IST] 00000610 SystemErr     R  at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:184)
[9/6/16 13:04:02:852 IST] 00000610 SystemErr     R  at com.box.sdk.BoxFolder.getInfo(BoxFolder.java:161)
[9/6/16 13:04:02:852 IST] 00000610 SystemErr     R  at com.edlore.box.util.GetFolderInfo.getFolderInfo(GetFolderInfo.java:19)
[9/6/16 13:04:02:852 IST] 00000610 SystemErr     R  at com.edlore.services.GetManualUrl.getAllSectionDetails(GetManualUrl.java:121)
[9/6/16 13:04:02:852 IST] 00000610 SystemErr     R  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[9/6/16 13:04:02:852 IST] 00000610 SystemErr     R  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:94)
[9/6/16 13:04:02:853 IST] 00000610 SystemErr     R  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
[9/6/16 13:04:02:853 IST] 00000610 SystemErr     R  at java.lang.reflect.Method.invoke(Method.java:619)
[9/6/16 13:04:02:853 IST] 00000610 SystemErr     R  at org.apache.wink.server.internal.handlers.InvokeMethodHandler.handleRequest(InvokeMethodHandler.java:63)
[9/6/16 13:04:02:853 IST] 00000610 SystemErr     R  at org.apache.wink.server.handlers.AbstractHandler.handleRequest(AbstractHandler.java:33)
[9/6/16 13:04:02:853 IST] 00000610 SystemErr     R  at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
[9/6/16 13:04:02:853 IST] 00000610 SystemErr     R  at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
[9/6/16 13:04:02:853 IST] 00000610 SystemErr     R  at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)

We doing operations are get Box Box Folder information.

**Comment by gcurtis** [comment]
Hi @adilakshmis, is this still an issue? If so, please reopen this ticket.

Looking at your stack trace, I can't see why this would be happening. You can also try the [Box Developer Forums](https://community.box.com/t5/Developer-Forum/bd-p/DeveloperForum). You might be able to get more help there around JWT authentication.
