### ISSUE TITLE
Unrecognized SSL message, plaintext connection?

### ISSUE THREAD

**Issue by kendomen** [box/box-java-sdk#318]
The same code ran fine in the US but when I'm here in Japan and I try to run it in Japan on my Mac, I get the below error.  When I'm vpn'd in on my PC, I don't get this error.

xception in thread "main" com.box.sdk.BoxAPIException: Couldn't connect to the Box API due to a network error.
	at com.box.sdk.BoxAPIRequest.writeBody(BoxAPIRequest.java:320)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:389)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:209)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:184)
	at com.box.sdk.BoxAPIConnection.refresh(BoxAPIConnection.java:464)
	at com.nike.box.BoxUpload.getBoxAPIConnection(BoxUpload.java:122)
	at com.nike.box.BoxUpload.main(BoxUpload.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at com.sun.net.ssl.internal.ssl.InputRecord.handleUnknownRecord(InputRecord.java:652)
	at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:484)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:863)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1188)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1215)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1199)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:476)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1031)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:230)
	at com.box.sdk.BoxAPIRequest.writeBody(BoxAPIRequest.java:309)
	... 11 more

**Comment by kendomen** [comment]
I found that this was a vpn issue
