### ISSUE TITLE
Box API intermittent failures - 404 and 502 errors. Default BackoffCounter doesn't help.

### ISSUE THREAD

**Issue by nddipiazza** [box/box-java-sdk#382]
Every now and then during a routine box api access using this java Box API, we get an error

```
Caused by: com.box.sdk.BoxAPIException: The API returned an error code: 502
                        at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:70)
                        at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:425)
                        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:209)
                        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:184)
                        at com.box.sdk.JSONIterator.loadNextPage(JSONIterator.java:74)
                        at com.box.sdk.JSONIterator.loadNextJsonObject(JSONIterator.java:90)
                        at com.box.sdk.JSONIterator.hasNext(JSONIterator.java:32)
                        at com.box.sdk.BoxItemIterator.hasNext(BoxItemIterator.java:28)
```

We notice before the error that there is the following in the log too indicating that it tried a backoff strategy to help but didn't work:

`Backing off for 2 seconds before retrying 2 more times.`
`Backing off for 4 seconds before retrying 1 more time.`

This is intermittent. When we try to reproduce, it's no longer happening and everything works fine. How can we make our Box API integration more robust and avoid these errors?

**Comment by gcurtis** [comment]
Hi @nddipiazza, this might've been an intermittent error with the Box API. Are you still consistently experiencing this issue?

**Comment by gcurtis** [comment]
Great! Thanks.
