### ISSUE TITLE
Error 400 while assigning number to field has type "float" use template

### ISSUE THREAD

**Issue by thoangtd** [box/box-java-sdk#401]
This is metadata : 
    Map<String,Object> properties = new HashedMap();
    properties.put("title", "file1.pdf");
    properties.put("author", "author 1");
    properties.put("subject", "subject 1");
    properties.put("category", "novel");
##     properties.put("amount", 2);

`
com.box.sdk.BoxAPIException: The API returned an error code: 409

	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:70)
	at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:30)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:423)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:209)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:184)
	at com.box.sdk.BoxFolder.uploadFile(BoxFolder.java:387)
	at com.box.sdk.BoxFolder.uploadFile(BoxFolder.java:334)
	at gov.nddot.cm.service.impl.BoxService.createDocument(BoxService.java:60)
	at gov.nddot.ce.box.CreateDocumentTests.initDocumentTest(CreateDocumentTests.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)`

**Comment by carycheng** [comment]
Hey @thoangtd, apologies for the late reply, I can take a look at this now and see what we find, thanks!

**Comment by carycheng** [comment]
Hey @thoangtd, the problem seemed to have been:

`jsonObject.add("/amount", 10)`

I replaced that line with this: 

`jsonObject.add("amount", 10)`

and it seems to have worked, everything else with your code is all right! 

Full code snippet below: 
```
    public void createMetadataTemplateSucceeds() {
        BoxAPIConnection api = new BoxAPIConnection("ACCESS_TOKEN_HERE");

        MetadataTemplate.Field amountField = new MetadataTemplate.Field();
        amountField.setType("float");
        amountField.setKey("amount");
        amountField.setDisplayName("Amount");

        List<MetadataTemplate.Field> fields = new ArrayList<MetadataTemplate.Field>();
        fields.add(amountField);

        MetadataTemplate template = MetadataTemplate.createMetadataTemplate(api, "enterprise", "TemplateTest", "Template Test", false, fields);
    }

    public void setFloatValueOnTemplateSucceeds() {
        BoxAPIConnection api = new BoxAPIConnection("ACCESS_TOKEN_HERE");
        BoxFile boxFile = new BoxFile(api, "FILE_ID_HERE");
        int customerAmount = 10

        final JsonObject jsonObject = new JsonObject();
        jsonObject.add("amount", customerAmount);

        Metadata customerMetadata = new Metadata(jsonObject);
        boxFile.createMetadata("TemplateTest", customerMetadata);
    }
```
