### ISSUE TITLE
OutOfMemoryError: Java heap space when using LargeFileUpload

### ISSUE THREAD

**Issue by gunicsba** [box/box-java-sdk#427]
Hello,

We get the following error:
```
Exception in thread "pool-15-thread-4" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.io.ByteArrayOutputStream.write(Unknown Source)
	at sun.net.www.http.PosterOutputStream.write(Unknown Source)
	at com.box.sdk.BoxAPIRequest.writeBody(BoxAPIRequest.java:327)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:401)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:221)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:196)
	at com.box.sdk.BoxFileUploadSession.uploadPart(BoxFileUploadSession.java:293)
	at com.box.sdk.LargeFileUploadTask.run(LargeFileUploadTask.java:44)
```
I'm not quite sure exactly which file caused this from our logs, but the file size is in the ballpark of: 100-270Mb

Prior to this we were able to upload files in the range of 1-2Gb (very-very slowly)

Thanks in advance

**Comment by iamharish** [comment]
Hi @Dezzsoke 

LargeFileUpload is similar to ExecutorService the more we create the thread count gets multiplied. Each file upload creates a set threads and if multiple files are being uploaded in parallel then the number of threads and thereby the heap usage will go up drastically and can cause this issue. Were you guys uploading files in parallel? And how many parallel connections were you using when creating LargeFileUpload
