### ISSUE TITLE
BoxFile.rename throws BoxAPIException after successful execution

### ISSUE THREAD

**Issue by cklab** [box/box-java-sdk#434]
I am using `box-java-sdk 2.3.0`. I have the following lines of code:

```
        String fileId = "...."; // insert any file id here
        BoxFile boxFile = new BoxFile(api, fileId);
        boxFile.rename("NewName");
```

Executing this line of code renames the file to "NewName" but then throws the exception:
```
Caused by: com.box.sdk.BoxAPIException: Couldn't finish closing the connection to the Box API due to a network error or because the stream was already closed.
	at com.box.sdk.BoxAPIResponse.disconnect(BoxAPIResponse.java:159)
	at com.box.sdk.BoxFile.rename(BoxFile.java:354)
	...
Caused by: java.io.IOException: stream is closed
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.ensureOpen(HttpURLConnection.java:3309)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3334)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3329)
	at com.box.sdk.BoxAPIResponse.disconnect(BoxAPIResponse.java:149)
	at com.box.sdk.BoxFile.rename(BoxFile.java:354)
        ...
```

**Comment by iamharish** [comment]
Unable to reproduce it
