### ISSUE TITLE
Error Code 400

### ISSUE THREAD

**Issue by smianatb** [box/box-java-sdk#435]
Getting The API returned an error code: 400 when trying to execute createAsUser Box Java SDK sample code.
Code is having trouble with the following line

        BoxDeveloperEditionAPIConnection api = BoxDeveloperEditionAPIConnection.getAppUserConnection(USER_ID, boxConfig, accessTokenCache);

maven dependencies are all added included JCE.

Exception in thread "main" com.box.sdk.BoxAPIException: The API returned an error code: 400
	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:70)
	at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:30)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:435)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:221)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:196)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:308)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:368)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(BoxDeveloperEditionAPIConnection.java:251)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(BoxDeveloperEditionAPIConnection.java:276)
	at com.atb.box.ASUser.main(ASUser.java:40)

**Comment by iamharish** [comment]
Can you check what's the error response. This can be found by calling getResponse() on BoxAPIException object

**Comment by smianatb** [comment]
Here is what I get.

{"error":"invalid_request","error_description":"Cannot obtain token based on the enterprise configuration for your app"}

looks like I am missing some configuration step in my app

**Comment by iamharish** [comment]
Well, that's the issue. Can be anything 
- check app configuration json and the actual configurations
- Check enterprise ID valid
- check if the app is authorized for the enterprise.
