### ISSUE TITLE
The API returned an error code: 400

### ISSUE THREAD

**Issue by VBulikov** [box/box-java-sdk#440]
Hello, got an error trying to connect to box with box-java-sdk. Problem was that it works fine on two different machines but gets an error on the third one with absolutely same credentials and settings.
Here`s error stacktrace. 

com.box.sdk.BoxAPIException: The API returned an error code: 400
    at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:70)
    at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:30)
    at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:423)
    at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:209)
    at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:184)
    at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:245)
    at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:305)
    at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(BoxDeveloperEditionAPIConnection.java:212)
    at AccessAsAppUser.downloadNewFile(AccessAsAppUser.java:40)
    at AccessAsAppUser.main(AccessAsAppUser.java:126)

**Comment by jack793** [comment]
You must configure your application in admin console like this guide suggest: [https://developer.box.com/v2.0/docs/configuring-box-platform](url)

**Comment by VBulikov** [comment]
Thanks for answer, @jack793, but i already did it. Absolutely same code works fine when i run it on another pc.

**Comment by iamharish** [comment]
@VBulikov Actual error response from the server will have details of why you are seeing a 400. Checkout method `getResponse` documented in 
[BoxAPIException](http://opensource.box.com/box-java-sdk/javadoc/com/box/sdk/BoxAPIException.html)

**Comment by VBulikov** [comment]
@iamharish Thanks, after googling this responce found a possible problem. Will try to solve it.
[`BoxApi`](https://community.box.com/t5/Box-Developer-Forum/Error-when-using-box-java-sdk/m-p/15536#M128)
