### ISSUE TITLE
Problem running the createappuser examples

### ISSUE THREAD

**Issue by adriannotimportant** [box/box-java-sdk#447]
Hi,

I'm running the example provided at https://github.com/box/box-java-sdk/blob/master/src/example/java/com/box/sdk/example/CreateAppUser.java.

The config.json file was created directly in: https://app.box.com/developers/console/app/383178/configuration as in the image below.

![image](https://user-images.githubusercontent.com/8119004/27672799-8dea3eaa-5ce0-11e7-9a3c-61bec6495cbe.png)

We are getting a:
com.box.sdk.BoxAPIException: The API returned an error code: 400

	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:70)
	at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:30)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:435)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:221)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:196)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:308)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:368)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:179)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:206)
	at com.nuix.data.box.TestBox.testCreadteAppUser(TestBox.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.nuix.common.test.rules.BaseTestRule$1.evaluate(BaseTestRule.java:45)
	at com.nuix.common.test.rules.BaseTestRule$1.evaluate(BaseTestRule.java:45)
	at com.nuix.common.test.rules.BaseTestRule$1.evaluate(BaseTestRule.java:45)
	at com.nuix.common.test.rules.BaseTestRule$1.evaluate(BaseTestRule.java:45)

That seems to be an out of the box use and we expected it to work. Any idea why is not working?

{"error":"invalid_request","error_description":"Cannot obtain user token based on the enterprise configuration for your app"}

Thank you in advance 
Adrian

**Comment by iamharish** [comment]
An app has to be authorized before it can be used
Follow steps mentioned here https://developer.box.com/v2.0/docs/configuring-box-platform
