### ISSUE TITLE
Error parsing PKCS private key for Box Developer Edition

### ISSUE THREAD

**Issue by DNSKishore** [box/box-java-sdk#451]
Hi Team,
I am working on authentication with JWT for the box.com
I have created a application and generated the config.json file (https://developer.box.com/docs/authentication-with-jwt#section-1-generating-an-rsa-keypair)
I have imported all the jar files that are required from the following link (https://github.com/box/box-java-sdk/blob/master/README.md) 
I am running a sample application to read the file of a user (https://github.com/box/box-java-sdk/blob/master/src/example/java/com/box/sdk/example/AccessAsAppUser.java)

I am facing "**Error parsing PKCS private key for Box Developer Edition**" 

Here is the error log.
Exception in thread "main" com.box.sdk.BoxAPIException: Error parsing PKCS private key for Box Developer Edition.
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:452)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:390)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:300)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:368)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(BoxDeveloperEditionAPIConnection.java:251)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(BoxDeveloperEditionAPIConnection.java:276)
	at com.box.sdk.example.Class1.main(Class1.java:38)
Caused by: org.bouncycastle.pkcs.PKCSException: unable to read encrypted data: 1.2.840.113549.1.5.13 not available: Illegal key size
	at org.bouncycastle.pkcs.PKCS8EncryptedPrivateKeyInfo.decryptPrivateKeyInfo(Unknown Source)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:441)
	... 6 more
Caused by: org.bouncycastle.operator.OperatorCreationException: 1.2.840.113549.1.5.13 not available: Illegal key size
	at org.bouncycastle.openssl.jcajce.JceOpenSSLPKCS8DecryptorProviderBuilder$1.get(Unknown Source)
	... 8 more
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1060)
	at javax.crypto.Cipher.init(Cipher.java:1536)
	at javax.crypto.Cipher.init(Cipher.java:1470)
	... 9 more
Process exited with exit code 1.

**Comment by iamharish** [comment]
Did you check #5?

> 
Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 7 If you don't install this, you'll get an exception about key length or exception about parsing PKCS private key for Box Developer Edition. This is not a Box thing, this is a U.S. Government requirement concerning strong encryption. The listed jar is for Oracle JRE. There might be other similar JARs for diffenrent JRE versions like the one below for IBM JDK Java Cryptography Extension for IBM JDK

**Comment by DNSKishore** [comment]
yes i have download the "**Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 7**" jar library files and added to my application. It throws the same error.

**Comment by DNSKishore** [comment]
These are the jar file i have used 
![image](https://user-images.githubusercontent.com/30169217/28200442-bb90ee8a-6889-11e7-83e1-30c224b5f49e.png)

**Comment by iamharish** [comment]
As mentioned in the doc, JCE has to be **installed** not copied in Java Home. JCE should replace the existing jars that JRE uses for parsing keys

Try steps mentioned below

https://stackoverflow.com/questions/41580489/how-to-install-unlimited-strength-jurisdiction-policy-files

**Comment by DNSKishore** [comment]
**Thanks Harish,**
The Parsing issue has been resolved but im facing a new error.

Here is the log
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.jose4j.jwa.AlgorithmFactoryFactory.<clinit>(AlgorithmFactoryFactory.java:34)
	at org.jose4j.jws.JsonWebSignature.getAlgorithm(JsonWebSignature.java:123)
	at org.jose4j.jws.JsonWebSignature.sign(JsonWebSignature.java:78)
	at org.jose4j.jws.JsonWebSignature.getCompactSerialization(JsonWebSignature.java:72)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:400)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:300)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:368)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(BoxDeveloperEditionAPIConnection.java:251)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(BoxDeveloperEditionAPIConnection.java:276)
	at com.box.sdk.example.Class1.main(Class1.java:38)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
Process exited with exit code 1.

**Comment by DNSKishore** [comment]
Hi,
I have found answer for the second error. Refer the following link 
https://stackoverflow.com/questions/18421091/exception-in-thread-main-java-lang-noclassdeffounderror-org-slf4j-iloggerfact
