### ISSUE TITLE
Exception in thread "main" com.box.sdk.BoxAPIException: The API returned an error code: 400

### ISSUE THREAD

**Issue by DNSKishore** [box/box-java-sdk#452]
Hi Team,
Im trying to run the sample code application to read the file of a user (https://github.com/box/box-java-sdk/blob/master/src/example/java/com/box/sdk/example/AccessAsAppUser.java)
I have imported all library jar files for running the application.

Im facing the following issue.
Exception in thread "main" com.box.sdk.BoxAPIException: The API returned an error code: 400
	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:70)
	at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:30)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:435)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:221)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:196)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:308)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:368)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(BoxDeveloperEditionAPIConnection.java:251)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(BoxDeveloperEditionAPIConnection.java:276)
	at com.box.sdk.example.Class1.main(Class1.java:38)
Process exited with exit code 1.

Kindly help me sort this issue

**Comment by iamharish** [comment]
An app has to be authorized before it can be usedFollow steps mentioned here https://developer.box.com/v2.0/docs/configuring-box-platform

**Comment by DNSKishore** [comment]
Hi Harish,
I have authorized the app as the document has said. But i am still facing the error. I have not added any new users to the app other than the admin. Is there any other steps i need to do.
![image](https://user-images.githubusercontent.com/30169217/28236473-05ed3dc4-6945-11e7-9ffc-ef6db05fc714.png)

**Comment by DNSKishore** [comment]
In the app authorization page its shows me like "0" users.
![image](https://user-images.githubusercontent.com/30169217/28236572-a5ca47b4-6946-11e7-8f20-b97bc3db7cd4.png)

**Comment by iamharish** [comment]
Did you create an App User?  Follow the README doc and try each example one after another in the order mentioned and you should be good to go. If you think something's missing in the doc, let us know

https://github.com/box/box-java-sdk/blob/master/README.md

**Comment by DNSKishore** [comment]
Thank you so much Harish i missed user creation.
