### ISSUE TITLE
Error# 400: Password reset required.

### ISSUE THREAD

**Issue by Narmu89** [box/box-java-sdk#456]
Hi Team, 

Am getting the below error when trying to create new App user,

gradle runCreateAppUser

> Task :runCreateAppUser
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.box.sdk.BoxAPIException: The API returned an error code: 400
{"error":"password_reset_required","error_description":"User needs to reset password"}
        at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:70)
        at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:30)
        at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:441)
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:227)
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:202)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:308)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:368)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:179)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:206)
        at com.box.sdk.example.CreateAppUser.main(CreateAppUser.java:38)

**Comment by mattwiller** [comment]
Hi @Narmu89 — can you give us a bit more information to help us troubleshoot what's going on here?  If possible, the following information would be helpful:

1. Which API call is getting the 400 — is this trying to get a token via JWT auth for the developer account, or some other account?
2. If the above is the case, can you try logging in as the account you used to create the application?  Does the password there need to be reset?  Currently, Box requires all developer account to have a minimum password strength of 8 characters with at least two of them being numbers.  Does updating the developer account password fix the issue?
