### ISSUE TITLE
com.box.sdk.BoxAPIException: Couldn't connect to the Box API due to a network error

### ISSUE THREAD

**Issue by DNSKishore** [box/box-java-sdk#457]
Hi Team,
I am facing network error while i'm running my upload file box code in my server.
Note : It works perfectly in my personal laptop but facing this issue in the server

Error log:
[2017-07-20T15:37:34.297+05:30] [AdminServer] [ERROR] [] [oracle.adfinternal.view.faces.webapp.rich.RegistrationFilter] [tid: [ACTIVE].ExecuteThread: '6' for queue: 'weblogic.kernel.Default (self-tuning)'] [userId: <anonymous>] [ecid: 7166e41f-c240-40b6-8cec-f6193d57730d-0000004d,0] [APP: BoxIntegrationApp_1] [partition-name: DOMAIN] [tenant-name: GLOBAL] [DSID: 0000LpVTq0oAPPWjLxbQ8A1PS83T000001] ADF_FACES-60096:Server Exception during PPR, #1[[
javax.servlet.ServletException: /BoxMain.jsf @9,93 action="#{backingBeanScope.BoxIntegrationBean.uploadFileToBox}": com.box.sdk.BoxAPIException: Couldn't connect to the Box API due to a network error.
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:663)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:286)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:350)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at oracle.adf.share.http.ServletADFFilter.doFilter(ServletADFFilter.java:77)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at oracle.adfinternal.view.faces.webapp.rich.RegistrationFilter.doFilter(RegistrationFilter.java:105)
	at org.apache.myfaces.trinidadinternal.webapp.TrinidadFilterImpl$FilterListChain.doFilter(TrinidadFilterImpl.java:529)
	at oracle.adfinternal.view.faces.activedata.AdsFilter.doFilter(AdsFilter.java:60)
	at org.apache.myfaces.trinidadinternal.webapp.TrinidadFilterImpl$FilterListChain.doFilter(TrinidadFilterImpl.java:529)
	at org.apache.myfaces.trinidadinternal.webapp.TrinidadFilterImpl._doFilterImpl(TrinidadFilterImpl.java:354)
	at org.apache.myfaces.trinidadinternal.webapp.TrinidadFilterImpl.doFilter(TrinidadFilterImpl.java:232)
	at org.apache.myfaces.trinidad.webapp.TrinidadFilter.doFilter(TrinidadFilter.java:92)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at oracle.security.jps.ee.http.JpsAbsFilter$1.run(JpsAbsFilter.java:141)
	at java.security.AccessController.doPrivileged(Native Method)
	at oracle.security.jps.util.JpsSubject.doAsPrivileged(JpsSubject.java:315)
	at oracle.security.jps.ee.util.JpsPlatformUtil.runJaasMode(JpsPlatformUtil.java:650)
	at oracle.security.jps.ee.http.JpsAbsFilter.runJaasMode(JpsAbsFilter.java:124)
	at oracle.security.jps.ee.http.JpsAbsFilter.doFilter(JpsAbsFilter.java:232)
	at oracle.security.jps.ee.http.JpsFilter.doFilter(JpsFilter.java:94)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at oracle.dms.servlet.DMSServletFilter.doFilter(DMSServletFilter.java:248)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:32)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3683)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3649)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:326)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2433)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2281)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2259)
	at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1691)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1651)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:270)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:348)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:333)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:54)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:640)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:406)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:346)
Caused by: javax.faces.el.EvaluationException: /BoxMain.jsf @9,93 action="#{backingBeanScope.BoxIntegrationBean.uploadFileToBox}": com.box.sdk.BoxAPIException: Couldn't connect to the Box API due to a network error.
	at org.apache.myfaces.trinidad.component.MethodExpressionMethodBinding.invoke(MethodExpressionMethodBinding.java:51)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
	at org.apache.myfaces.trinidad.component.UIXCommand.broadcast(UIXCommand.java:190)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at oracle.adfinternal.view.faces.lifecycle.LifecycleImpl._invokeApplication(LifecycleImpl.java:1243)
	at oracle.adfinternal.view.faces.lifecycle.LifecycleImpl._executeInvokeApplication(LifecycleImpl.java:686)
	at oracle.adfinternal.view.faces.lifecycle.LifecycleImpl._executePhase(LifecycleImpl.java:364)
	at oracle.adfinternal.view.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:227)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:650)
	... 47 more
Caused by: com.box.sdk.BoxAPIException: Couldn't connect to the Box API due to a network error.
	at com.box.sdk.BoxAPIRequest.writeBody(BoxAPIRequest.java:332)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:401)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:221)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:196)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:308)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:368)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(BoxDeveloperEditionAPIConnection.java:251)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(BoxDeveloperEditionAPIConnection.java:276)
	at bx.app.view.bean.BoxIntegrationBean.uploadFileToBox(BoxIntegrationBean.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:181)
	at com.sun.el.parser.AstValue.invoke(AstValue.java:289)
	at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
	at org.apache.myfaces.trinidad.component.MethodExpressionMethodBinding.invoke(MethodExpressionMethodBinding.java:46)
	... 56 more
Caused by: java.net.UnknownHostException: api.box.com: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at weblogic.net.http.HttpsClient.openServer(HttpsClient.java:269)
	at weblogic.net.http.HttpsClient.openServer(HttpsClient.java:361)
	at weblogic.net.http.HttpsClient.New(HttpsClient.java:564)
	at weblogic.net.http.HttpsClient.New(HttpsClient.java:545)
	at weblogic.net.http.HttpsURLConnection.connect(HttpsURLConnection.java:236)
	at weblogic.net.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:375)
	at com.box.sdk.BoxAPIRequest.writeBody(BoxAPIRequest.java:321)
	... 73 more

**Comment by DNSKishore** [comment]
Hi team,
Its due to my server firewall issue.
Issue resolved.

Thanks,
