### ISSUE TITLE
Cannot restore a trashed folder

### ISSUE THREAD

**Issue by kernelogic** [box/box-java-sdk#477]
Hello when I try to restore a folder, i get this response. It's not documented in the api.

com.box.sdk.BoxAPIException: The API returned an error code: 411
<HTML>
<HEAD>
<TITLE>No Content Length</TITLE>
</HEAD>

<BODY BGCOLOR="white" FGCOLOR="black">
<H1>No Content Length</H1>
<HR>

<FONT FACE="Helvetica,Arial"><B>
Description: Could not process this request because
there was no Content-Length specified.
</B></FONT>
<HR>
</BODY>

	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:85) ~[box-java-sdk-2.8.2.jar:na]
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:481) ~[box-java-sdk-2.8.2.jar:na]
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:265) ~[box-java-sdk-2.8.2.jar:na]
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:240) ~[box-java-sdk-2.8.2.jar:na]
	at com.box.sdk.BoxTrash.restoreFolder(BoxTrash.java:100) ~[box-java-sdk-2.8.2.jar:na]

**Comment by carycheng77** [comment]
Hey @kernelogic, thank you for reaching out and apologies for this error, we are working on a patch right now!

**Comment by mattwiller** [comment]
This should be fixed by #495 — we'll put together a release with this fix in it once some of the other major changes we have in flight land!
