### ISSUE TITLE
public BoxFolder.Info moveFolderToUser​(String sourceUserID) : Couldn't finish closing the connection to the Box API due to a network error or because the stream was already closed.

### ISSUE THREAD

**Issue by abhi8344** [box/box-java-sdk#481]
I am using the box java sdk 2.8.2 to move some folders around as a part of automation.

A call to public BoxFolder.Info moveFolderToUser​(String sourceUserID) throws the following exception . The move happens succesfully but the BoxFolder.Info object returned is null. 

com.box.sdk.BoxAPIException: Couldn't finish closing the connection to the Box API due to a network error or because the stream was already closed.
at com.box.sdk.BoxAPIResponse.disconnect(BoxAPIResponse.java:192)
at com.box.sdk.BoxUser.moveFolderToUser(BoxUser.java:445)
at com..box.BoxTermProcessAutomation.moveTerminatedUserFolders(BoxTermProcessAutomation.java:430)
at com..box.BoxTermProcessAutomation.main(BoxTermProcessAutomation.java:59)
Caused by: java.io.IOException: stream is closed
at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.ensureOpen(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
at com.box.sdk.BoxAPIResponse.disconnect(BoxAPIResponse.java:182)
... 3 more

**Comment by carycheng77** [comment]
#485

**Comment by abhi8344** [comment]
When will the jar with the fix be available for download ?

**Comment by carycheng77** [comment]
Hey @abhi8344, we are waiting for one more feature to be merged and after that we will do a release. We are aiming for end of this week/early next week. 

Thanks!
