### ISSUE TITLE
Running on JDK 1.6: UnsupportedClassVersionError: org/jose4j/lang/JoseException : Unsupported major.minor

### ISSUE THREAD

**Issue by kylefernandadams** [box/box-java-sdk#482]
The sourceCompatibility = 1.6, however there seems to be an issue with the jose4J dependency when running on JDK 1.6.

```
java.lang.UnsupportedClassVersionError: org/jose4j/lang/JoseException : Unsupported major.minor version 51.0 (unable to load class org.jose4j.lang.JoseException)
        at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2726)
        at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1124)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1612)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1491)
        at com.ssc.box.BoxUtility.getBoxConnection(Unknown Source)
        at com.ssc.cdt.box.BoxUtil.<init>(BoxUtil.java:52)
        at com.ssc.cdt.mq.MSGHandler.handleMessage(MSGHandler.java:195)
        at com.ssc.brm.common.email.mq.handler.BaseHandler.handleMQMessage(BaseHandler.java:22)
        at com.ssc.bpms.utils.ibmmq.QueueListener.run(QueueListener.java:132)
```

**Comment by cburnette** [comment]
I believe in order to support the JWT stuff that was added a while back the SDK needed to move up to 1.7 and greater.

**Comment by kylefernandadams** [comment]
Understood. If that's the case, then we should update the gradle.build file to have the min version of 1.7 and would love to see a table that shows compatibility between JDK versions and SDK versions to make things clear.
