### ISSUE TITLE
Chunked Upload stream closing error

### ISSUE THREAD

**Issue by jessicaviki** [box/box-java-sdk#579]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Using the Box V2 SDK for Chunked Uploads and I'm getting the following error in "UploadPartAsync" method: **System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a closed Stream.**
I'll include my log statements and stack trace below. I'm attempting to send a 50MB file (also happens on all files I try) using Chunked Uploading. It's sending all 7 parts and getting a 200 response back for all parts. but then after the last part, the session commit doesn't happen and I get the above closed Stream error. 
Wondering if you've seen this before? It seems like it's trying to call UploadPartAsync an 8th time after the stream is already closed. I had it working a couple weeks ago with the same files (>20MB), but now can't send any. I haven't changed any of the code between it working and not working. 

### Versions Used
Java SDK: Box.V2 3.4.2
Java: Version 8, Update 161

### Steps to Reproduce
Steps to reproduce are to hit Archive project on our web application. 
Flow of SDK methods being called are: UploadUsingSessionAsync, which first calls CreateUploadSessionAsync (successfully creates Upload session), then UploadSessionAsync > UploadPartsInSessionAsync > UploadPartAsync (failing here after last part gets sent). It should then call CommitSessionAsync but it's not getting there.

### Error Message, Including Log Statements and Stack Trace
22-Mar-18	10:40:35.687	<Debug>	[Viki.sProcessingQueue.18068.50]	{History}	Job "New Archive test" has been queued for archiving
22-Mar-18	10:40:38.055	<Info>	[Viki.sProcessingQueue.18068.8]	{Archiving}	Archiving file 	SCTZ-0524.pdf	, attempt 	1	 of 	3	
22-Mar-18	10:40:38.056	<Debug>	[Viki.sProcessingQueue.18068.8]	{Archiving}	Creating Upload session with uri 	https://upload.box.com/api/2.0/files/upload_sessions	
22-Mar-18	10:40:39.059	<Debug>	[Viki.sProcessingQueue.18068.42]	{Archiving}	Uploading File part 	0	-	8388607	/	50773750	
22-Mar-18	10:40:39.106	<Debug>	[Viki.sProcessingQueue.18068.42]	{Archiving}	Uploading File part 	8388608	-	16777215	/	50773750	
22-Mar-18	10:40:39.150	<Debug>	[Viki.sProcessingQueue.18068.42]	{Archiving}	Uploading File part 	16777216	-	25165823	/	50773750	
22-Mar-18	10:40:39.190	<Debug>	[Viki.sProcessingQueue.18068.42]	{Archiving}	Uploading File part 	25165824	-	33554431	/	50773750	
22-Mar-18	10:40:39.229	<Debug>	[Viki.sProcessingQueue.18068.42]	{Archiving}	Uploading File part 	33554432	-	41943039	/	50773750		
22-Mar-18	10:40:49.639	<Debug>	[Viki.sProcessingQueue.18068.23]	{Archiving}	Uploading File part 	41943040	-	50331647	/	50773750	
22-Mar-18	10:40:50.408	<Debug>	[Viki.sProcessingQueue.18068.35]	{Archiving}	Uploading File part 	50331648	-	50773749	/	50773750	
22-Mar-18	10:41:11.647	<Error>	[Viki.sProcessingQueue.18068.8]	{Archiving}	Caught exception in UploadFile, destinationPath 	\Bass\Jobs\New_Archive_test-1095\FileTransfers\1267	, path 	c:\DataStores\Root\Bass\Jobs\New_Archive_test-1095\FileTransfers\1267\SCTZ-0524.pdf	, exception 	System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.get_Length()
   at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadPartAsync>d__3.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 896
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadPart>d__9.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 1120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadPartsInSessionAsync>d__8.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 1103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadSessionAsync>d__7.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 1011
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadUsingSessionAsync>d__6.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 971
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Viki.bBase.bnJobArchiver.bcBoxDotComArchiver.UploadFile(String destinationPath, String path) in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 414
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.get_Length()
   at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadPartAsync>d__3.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 896
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadPart>d__9.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 1120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadPartsInSessionAsync>d__8.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 1103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadSessionAsync>d__7.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 1011
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Viki.bBase.bnJobArchiver.BoxFilesManager.<UploadUsingSessionAsync>d__6.MoveNext() in C:\Repositories\Main\Common\bBase\bnJobArchiver\bcBoxDotComArchiver.cs:line 971<---

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @jessicaviki, thanks for letting us know, we'll take a look at this and follow up

**Comment by carycheng** [comment]
This is a box-windows-sdk issue, we have moved it over there and can be found at this link

https://github.com/box/box-windows-sdk-v2/issues/463
