### ISSUE TITLE
Some BoxItem.Info properties return null value when iterating all items in a Folder.

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#618]
- [ X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
BoxFolder.getInfo() populates some values to BoxFolder object properties but when iterating those as per suggested code in the API documentation some of the properties are giving null values. 

### Versions Used
Java SDK:   2.20.1
Java: "1.8.0_131"

### Steps to Reproduce
Example: In my test owned_by is null when iterating. See my sample code below. The exception handling shows that the owned_by is retrieved correctly when directly accessing BoxFolder.getInfo().

for (BoxItem.Info itemInfo : folder) {
			if (itemInfo instanceof BoxFile.Info) {
				BoxFile.Info fileInfo = (BoxFile.Info) itemInfo;
				// Do something with the file.
			} else if (itemInfo instanceof BoxFolder.Info) {
				BoxFolder.Info folderInfo = (BoxFolder.Info) itemInfo;
				try {
					System.out.println(folderInfo.getOwnedBy().getLogin());
				} catch (Exception e) {
					e.printStackTrace();
					BoxFolder folderE = new BoxFolder(wsUserApi, folderInfo.getID());
					System.out.println(folderE.getInfo().getOwnedBy().getLogin());
				}
			}
		}

### Error Message, Including Stack Trace
java.lang.NullPointerException
	at TestPinyonJavaSDK.displayFolderOwner(TestBoxJavaSDK.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @rjainrohit, 

I would use the `getChildren()` function on BoxFolder which takes in the fields you wish to retrieve like below. 

```Java
        BoxFolder folder = new BoxFolder(api, "FOLDER_ID_HERE");

        Iterable<BoxItem.Info> itemsInFolder = folder.getChildren("owned_by");
        for (BoxItem.Info itemInfo : itemsInFolder) {
            if (itemInfo instanceof BoxFolder.Info) {
                System.out.println("Attributes: " + itemInfo.getOwnedBy().getLogin());
            } else {
                // Do something with file
            }
        }
```

Let us know if this resolves you issue, thanks!

**Comment by rjainrohit** [comment]
Thanks !!!
