### ISSUE TITLE
BoxAPIConnection returns 407 AuthenticationRequired

### ISSUE THREAD

**Issue by arpithaar** [box/box-java-sdk#637]
### Description of the Issue
Team,

I am using the code snippet [1] to establish connection to api.box.com. Our environment has a proxy server setup with Basic and NTLM Authentication schemes. All outbound connections go via proxy and hence I had to set the proxy object to BoxAPIConnection. The requests are failing at Proxy server and returns 407 HTTP response [2]. I doubt that the proxy username and password set to BoxApiConnection are not getting set in the connection request and hence proxy Authentication Error.
The code works fine when executed in a standalone java class but unable to connect to proxy when deployed in Jetty web server.
I tried to connect using Apache HttpClient APIs and it works standalone as well as in web server.

Note: I am using Standard OAuth 2.0 . If I change the implementation to use Webhooks, will it be using the same BoxAPIConnection(or java.net.HttpURLConnection) API?

Is this something you can help ?

[1] **Code Snippet:**
 BoxAPIConnection api = new BoxAPIConnection("access_token");
 Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxy-host-name", port));
 api.setProxy(proxy);
 api.setProxyUsername("proxy_user_name");
 api.setProxyPassword("proxy_password");

[2] **Exception**
		```
com.box.sdk.BoxAPIException: Couldn't connect to the Box API due to a network error.
        at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:523) [com.sample.core:1.0.1.SNAPSHOT]
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:326) [com.sample.core:1.0.1.SNAPSHOT]
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:301) [com.sample.core:1.0.1.SNAPSHOT]
        at com.box.sdk.BoxUser.getCurrentUser(BoxUser.java:163) [com.sample.core:1.0.1.SNAPSHOT]
        at com.sample.schedulers.BoxImportScheduler.run(BoxImportScheduler.java:184) [com.sample.core:1.0.1.SNAPSHOT]
        at org.apache.sling.commons.scheduler.impl.QuartzJobExecutor.execute(QuartzJobExecutor.java:347) [org.apache.sling.commons.scheduler:2.7.2]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org.apache.sling.commons.scheduler:2.7.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 AuthenticationRequired"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2085)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
        at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:521) [com.sample.core:1.0.1.SNAPSHOT]
        ... 9 common frames omitted
```

### Versions Used
Box Java SDK: 2.21.0
Java: 1.8.0_172

**Comment by carycheng** [comment]
Hey @arpithaar, 

Thank you for writing in, we will look into this.

Thank you!
