### ISSUE TITLE
Nullpointer exception

### ISSUE THREAD

**Issue by ajayaks** [box/box-java-sdk#643]
Hi, 
I am getting Nullpointer as below. Its reading the json file but not getting connection. Referring example in GitHub.

IAccessTokenCache accessTokenCache = new InMemoryLRUAccessTokenCache(MAX_CACHE_ENTRIES);

        Reader reader = new FileReader("/Users/<name>/<json>");
        BoxConfig boxConfig = BoxConfig.readFrom(reader);

        BoxDeveloperEditionAPIConnection api = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig, accessTokenCache);

Exception in thread "main" java.lang.NullPointerException
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:462)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:405)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:315)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:383)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:194)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:221)
	at com.apple.ist.es.insight.services.BoxAccessAsAppUser.main(BoxAccessAsAppUser.java:38)

**Comment by carycheng** [comment]
Hey @ajayaks, 

We just tried out this call and it seems to be okay, wanted to check to make sure that the config.json file you are passing in contains the private key? 

It should look like this format:
```{
  "boxAppSettings": {
    "clientID": "",
    "clientSecret": "",
    "appAuth": {
      "publicKeyID": "",
      "privateKey": "",
      "passphrase": ""
    }
  },
  "enterpriseID": ""
}

**Comment by ajayaks** [comment]
Hi Cary, 

I have tried with with and without private key in config json file.

{
  "boxAppSettings": {
    "clientID": "<as on my account on box>",
    "clientSecret": "<as on my account on box>",
    "appAuth": {
      "publicKeyID": "<as on my account on box>",
      "privateKey": "<xxxxxxx>",
      "passphrase": "<as on my account on box>"
    }
  },
  "enterpriseID": "<as on my account on box>"
}

Do I have to use authorize the application in box ?

I am able to generate the access token via grant type = "authorization code".
Is there any via I can test grant type = "client credential" from postman? I am getting client credentials are not valid.

Regards
Ajay

**Comment by carycheng** [comment]
Hey @ajayaks, 

You do need to authorize the application inside Box. 

This guide [here](https://community.box.com/t5/How-to-Guides-for-Admins/Enabling-Custom-Built-Applications/ta-p/2188) will walk you through how to do this.

However, you should not be getting a NullPointerException error if your app is not authorized. Are you still receiving that same error?

**Comment by ajayaks** [comment]
I think we can close this issue, I am not using JWT currently hence didn't look into this after that .
Thanks for your support.
