### ISSUE TITLE
Getting collaborator information

### ISSUE THREAD

**Issue by saadali5997** [box/box-java-sdk#699]
#### Problem

Hi,

I am trying to to get details of a collaborator in a collaboration for a folder and I am only able to get one of the required fields.

#### Detail
I was trying to get users and their permissions for files and folders. For files I used this
`file.getAllFileCollaborations` and the for each collaboration `col` I did:
```
col.getAccessibleBy.getName, col.getRole.toString
```
and it works like a charm. But when I try to do the same thing for a folder:
```
folder.getCollaborations
``` 
and then for each collaboration `col`, when I do `col.getRole` it gives me the role as expected but when I do `col.getAccessibleBy.getName` it throws an exception: 
```
Exception in thread "main" java.lang.NullPointerException
```
#### Some troubleshoot infromation
When I try to achieve the same thing from the same token through postman, I get the expected result, and the name of that collaborator for whom I get this exception is there in the response.
**Here I must tell you one more thing**, that I am not the owner of that folder, I am the editor, but if I am seeing the information in postman response, I must be able to see that in java SDK API's function too.

#### Versions Used
Java SDK: 2.32.0
Java: 8
#### Steps to Reproduce
1. Make a folder.
`val folder = new BoxFolder(api, itemId)`
2. Get it's collaborations
`val collaborations = folder.getCollaborations`
3. Try to get name of a collaborator
```
collaborations.foreach { col =>
          println(s"${col.getAccessibleBy.getName}, ${col.getRole.toString}")
        }
```

#### Error Message, Including Stack Trace
```
Exception in thread "main" java.lang.NullPointerException
	at com.datumbrain.MainClass$.$anonfun$main$3(MainClass.scala:34)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.datumbrain.MainClass$.$anonfun$main$1(MainClass.scala:33)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.datumbrain.MainClass$.main(MainClass.scala:20)
	at com.datumbrain.MainClass.main(MainClass.scala)

```

Here's the complete `Scala` snippet of the `folder` code:
```
val folder = new BoxFolder(api, itemId)
folder.getCollaborations.foreach { col =>
  println(s"${col.getAccessibleBy.getName}, ${col.getRole.toString}")
}
```

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@saadali5997 I'm not able to reproduce this issue in my environment, so I'll need some more information from you to diagnose what the issue might be:
- When you make the request manually in Postman, can you double-check that you're using the exact same account and folder?
- Since you're printing from each collaboration in the collection, can you cross-check against the response from Postman to see which collaboration in the response might be causing the issue?  If there is a specific one that's failing, can you show me what it looks like (after redacting any sensitive or identifying information)?

**Comment by saadali5997** [comment]
> @saadali5997 I'm not able to reproduce this issue in my environment, so I'll need some more information from you to diagnose what the issue might be:
> 
> * When you make the request manually in Postman, can you double-check that you're using the exact same account and folder?
> * Since you're printing from each collaboration in the collection, can you cross-check against the response from Postman to see which collaboration in the response might be causing the issue?  If there is a specific one that's failing, can you show me what it looks like (after redacting any sensitive or identifying information)?

Hi @mattwiller !
So the folder I was having issue with was owned by someone else and was shared with me as *EDITOR*. I was able to get my information and owner information from the folder, but was not able to get information of other people it was shared with. Getting information of that particular third collaborator was causing the problem, being not the *OWNER* of the folder myself.
Anyway, I wrote a default case for it, decided to handle it later and integrated in my app and it worked there. I know it seems weird, but it works there, the same code.
Thanks for your time. I will close the issue now.
