### ISSUE TITLE
Occasionally large move of a folder causes BoxAPIException with null response and 0 responseCode

### ISSUE THREAD

**Issue by alkleela** [box/box-java-sdk#709]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Occasionally large move of a folder causes BoxAPIException with null response and 0 responseCode 

### Versions Used
Java SDK: 2.30.1
Java: java 1.8

### Steps to Reproduce
 Have a folder with 15 sub folders and each having  around 1000+ files in it and  call (new BoxFolder(apiConnection, <origin folder rid>).move(new BoxFolder(apiConnection,<destination folder id).
This results in a BoxAPIException with response null and responseCode:0  

### Error Message, Including Stack Trace
BoxAPIException with response null and responseCode:0 .

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @alkleela, 

What you are encountering is a timeout error, unfortunately that is not something that we can handle for on our side. We apologize for the confusing error message. And we will work on better error messaging in the SDK to avoid confusing or non-explicit error messages like what you have seen.

**Comment by lorenzobenvenuti** [comment]
Hi,

we're facing a similar issue. Every now and then a call to Box (either download file or list folder items) fails with code 0 and null body; the root cause is

```
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_242]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_242]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_242]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_242]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_242]
	at java.net.Socket.connect(Socket.java:607) ~[na:1.8.0_242]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666) ~[na:1.8.0_242]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_242]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_242]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_242]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[na:1.8.0_242]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[na:1.8.0_242]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_242]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[na:1.8.0_242]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[na:1.8.0_242]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_242]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167) ~[na:1.8.0_242]
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:449) ~[box-java-sdk-2.10.0.jar!/:na]
```

We've seen that when this error pops up, the request lasts more or less two minutes... but:
- We are not setting any timeout so I think the request should use default values set in `BoxGlobalSettings`, which are `0` => infinite timeout
- It's not an infrastructure issue, at least on our side: our application is performing requests lasting longer than two minutes without issues.

You say "that is not something that we can handle for on our side", do you mean there's "something" (reverse proxy, load balancer) on Box side that drops all the connections lasting longer than two minutes?

Thanks!

lorenzo
