### ISSUE TITLE
Maximo system cannot connect to Box:- org.apache.commons cannot be resolved

### ISSUE THREAD

**Issue by manishACN** [box/box-java-sdk#740]
Oct 10, 2019 5:31:02 PM com.box.sdk.BoxAPIRequest <init>
WARNING: Unable to set up SSL context for HTTPS!  This may result in the inability  to connect to the Box API.
Oct 10, 2019 5:31:02 PM org.jose4j.jwa.AlgorithmFactoryFactory initialize
INFO: Initializing jose4j (running with Java 1.6.0_45 from Sun Microsystems Inc. at C:\Program Files\Java\jre6 with [SUN version 1.6, SunRsaSign version 1.5, SunJSSE version 1.6, SunJCE version 1.6, SunJGSS version 1.0, SunSASL version 1.5, XMLDSig version 1.0, SunPCSC version 1.6, SunMSCAPI version 1.6, BC version 1.52] security providers installed)...
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The import org.apache.commons cannot be resolved
	The import org.apache.commons cannot be resolved
	Log cannot be resolved to a type
	LogFactory cannot be resolved

	at org.jose4j.jwa.AlgorithmInfo.<init>(AlgorithmInfo.java:19)
	at org.jose4j.jws.PlaintextNoneAlgorithm.<init>(PlaintextNoneAlgorithm.java:35)
	at org.jose4j.jwa.AlgorithmFactoryFactory.initialize(AlgorithmFactoryFactory.java:63)
	at org.jose4j.jwa.AlgorithmFactoryFactory.<init>(AlgorithmFactoryFactory.java:45)
	at org.jose4j.jwa.AlgorithmFactoryFactory.<clinit>(AlgorithmFactoryFactory.java:36)
	at org.jose4j.jws.JsonWebSignature.getAlgorithm(JsonWebSignature.java:123)
	at org.jose4j.jws.JsonWebSignature.sign(JsonWebSignature.java:78)
	at org.jose4j.jws.JsonWebSignature.getCompactSerialization(JsonWebSignature.java:72)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:460)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:431)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:320)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.refresh(BoxDeveloperEditionAPIConnection.java:395)
	at com.box.sdk.BoxAPIConnection.lockAccessToken(BoxAPIConnection.java:757)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:490)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:326)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:301)
	at com.box.sdk.BoxSearch.searchRange(BoxSearch.java:44)
	at Cert.Download.downloadJson.main(downloadJson.java:78)

**Comment by carycheng** [comment]
Hey @manishACN,

Thank you for writing in. Please use the template that is present on the Github issue page when submitting a new issue as this will give us more context to assist you better.

At a quick glance for this issue it seems like something within the set up and not
necessarily a bug in the SDK. Unfortunately, it's pretty difficult to debug environments as we do not have the access nor the context.

However, at a glance it seems like an issue importing the packages you are using. Be sure to include any library you use either as a Maven Dependency or as a JAR in your class path for your project.

**Comment by PJSimon** [comment]
Hi @manishACN,

I just wanted to check in and see how it's going.  Is this issue resolved for you?

Thanks,

Patrick

**Comment by PJSimon** [comment]
Hi @manishACN,

I'm going to close this issue since we haven't heard from you in a while.  If you're still having issues, please just re-open the issue!

Thanks,

Patrick
