### ISSUE TITLE
Box SDK pac proxy

### ISSUE THREAD

**Issue by mklinchin** [box/box-java-sdk#757]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Versions Used
Java SDK: 
Java: 

### Error Message, Including Stack Trace

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by mklinchin** [comment]
Hello Guys. I have an issue with proxy on java BOX SDK 2.20.1 version, but I do not think that newest version has some fixes about that. I can't go through proxy if proxy configured with pac file. The only proxy that I can specify in SDK is host/port and login/password. Thus I have next error:

Caused by: java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.box.boxjavalibv2.BoxRESTClient.getResponse(BoxRESTClient.java:148)
	at com.box.boxjavalibv2.BoxRESTClient.execute(BoxRESTClient.java:98)

As I know apache HttpClient doesnt support pac file itself, but java itself - does, so If I'd construct request by myself and post it with pure java it'll go throught proxy successfully. So tell me please if this possible at all to use your BOX SDK with proxy pac file, Thank you in advance!

**Comment by carycheng** [comment]
Hey @mklinchin, currently the Java SDK only supports basic proxy. Adding additional proxy avenues is something that we have thought about and hear feedback on. We will definitely take into consideration down the road. However, as of today the Java SDK only supports basic proxy.

If there is something I’ve misunderstood or have missed context on please let me know!

Thank you!

**Comment by PJSimon** [comment]
Hi @mklinchin, closing this issue as it seems resolved.  Please feel free to re-open if you'd like to discuss further!  Thanks!
