### ISSUE TITLE
box delete a folder using java sdk giving me 401 error code

### ISSUE THREAD

**Issue by bdv1234** [box/box-java-sdk#763]
- I have checked the SDK documentation but it doesn't solve my issue

### Description of the Issue
I'm trying to delete a folder in box using java sdk. for authentication mechanism I'm using Developer token which only valid for 1 hour. I tried to delete the same folder which I'm want to delete using delete API, it works fine. but in my java code it didn't work as expected.

### Versions Used
Java SDK: box-java-sdk version 2.32.0
Java: SE 8 in Centos 7 platform

### Steps to Reproduce

1.  first I have registered the app in developer box and I got the developer access token which is a bearer token.
2.  My application is spring boot. so I have put the token in application.property file and whenever I need in service class , I get the token from application.properties file.
3.  I have debugged the application and all the expected variables initialized successfully.
4.  In java sdk for box, in delete method I pass the folder id which is String through REST Controller.

following is my code to delete the folder.

` 

    @Value(value = "${developer.access.token}")
    private String token;

    private BoxAPIConnection boxAPIConnection = new BoxAPIConnection(this.token);

    @Override
    public void deleteAFolder(String folderId) {
        LOGGER.info("inside the folder delete method. with id {} ", folderId);
        // delete the folder and it's content
        BoxFolder folder = new BoxFolder(boxAPIConnection, folderId);
        folder.delete(true);
    }
`

### Error Message, Including Stack Trace
2020-01-01 15:51:19.023 ERROR 19573 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.box.sdk.BoxAPIResponseException: The API returned an error code [401 | .0e2bd0b9fc9a32eb43cef1763ec8ea5fb]] with root cause

com.box.sdk.BoxAPIResponseException: The API returned an error code [401 | .0e2bd0b9fc9a32eb43cef1763ec8ea5fb]
	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:92) ~[box-java-sdk-2.32.0.jar!/:na]
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:577) ~[box-java-sdk-2.32.0.jar!/:na]
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:354) ~[box-java-sdk-2.32.0.jar!/:na]
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:329) ~[box-java-sdk-2.32.0.jar!/:na]
	at com.box.sdk.BoxFolder.delete(BoxFolder.java:374) ~[box-java-sdk-2.32.0.jar!/:na]
	at com.persistent.boxapp.services.FolderImpl.deleteAFolder(FolderImpl.java:35) ~[classes!/:0.0.1-SNAPSHOT]
	at com.persistent.boxapp.controller.FolderController.deleteAFolder(FolderController.java:26) ~[classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_221]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:931) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:666) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.29.jar!/:9.0.29]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @bdv1234,

A 401 error means that the token you are using is no longer authorized. Depending on which authentication scheme you are using in your Java code from [here](https://github.com/box/box-java-sdk/blob/master/doc/authentication.md) you will have to refresh your access token before making a call to delete the folder.

**Comment by bdv1234** [comment]
@carycheng ,
I'm using developer token for authentication. documentation says that I don't need to refresh it. It only valid for 1 hour. 

> A developer token is simply a short-lived access token that cannot be  refreshed

let's say after 1 hour it expired, what I have did  was revoke the developer token and generate a new token again and use that token to make api calls.

**Comment by carycheng** [comment]
Ah I see - 

So to make sure I understand your current flow - 
- You are going into the developer console and clicking on the "Generate Developer Token" button to retrieve a 1 hour short lived token. 
- After that you are using the token to make a call to delete a folder
- After one hour when the token expires you go back into the Developer Console and click the "Revoke Token" button and then generate a new developer token and continue making calls with that newly generated token

Let me know if the above flow is similar to what your are currently doing. As for when you get the 401 error is it after you have generated a new developer token?

I am specifically referring to your above step:

```
My application is spring boot. so I have put the token in application.property file and whenever I need in service class , I get the token from application.properties file.
```

Curious when you update your application.property file with the new token after the initial token expires?

Thank you for the information

**Comment by bdv1234** [comment]
@carycheng ,
your mentioned step are exactly matching with my steps.
yes, each time I generate a developer token I update my application.properties file.

**Comment by carycheng** [comment]
Thank you for the information @bdv1234.

Getting a 401 error most likely falls on the application set up side, if you are using a developer token and replacing it when necessary that might be causing complications inside your app for instance if you are caching the older tokens.

In longer running applications where you expect to come back and run often we recommend you use one of our authentication schemes listed above as the Developer Token is only recommended for testing purposes or one off usages.

Please refer to this guide [here](https://developer.box.com/en/guides/authentication/) learn more about different auth types provided by Box and find one that suits your use case. After that, please refer to [here](https://github.com/box/box-java-sdk/blob/master/doc/authentication.md) to learn about how to implement the authentication type with the Box Java SDK

Thank you

**Comment by bdv1234** [comment]
@carycheng ,
after many hours of debugging I found the error which is related to object creation in spring. 
every time access token set to null, hence giving me the error code 401.
I was able to resolve my problem.
thank you for your replies.
cheers !

**Comment by carycheng** [comment]
Really glad to hear this was revolved @bdv1234!

Please don’t hesitate to reach out if you have any other questions about the Box Java SDK
