### ISSUE TITLE
unable to run the CreateAppUser

### ISSUE THREAD

**Issue by amitbatajoo** [box/box-java-sdk#796]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

Hello,
When I run this gradle, I got the error.
I am really new in Box api, can anyone please let me know what is the problem and how to 
solve and able to run the code.

F:\DevApp\box-java-sdk-master>gradle runCreateAppUser

> Task :runCreateAppUser FAILED
Exception in thread "main" java.lang.RuntimeException: An invalid token URL indicates a bug in the SDK.
        at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:321)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:468)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:203)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:230)
        at com.box.sdk.example.CreateAppUser.main(CreateAppUser.java:38)
Caused by: java.net.MalformedURLException: no protocol:
        at java.base/java.net.URL.<init>(URL.java:657)
        at java.base/java.net.URL.<init>(URL.java:553)
        at java.base/java.net.URL.<init>(URL.java:500)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:318)
        ... 4 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runCreateAppUser'.
> Process 'command 'C:\Program Files\Java\jdk-12.0.2\bin\java.exe'' finished with non-zero exit value 1

Please please help me

Thank you in advance.!

**Comment by PJSimon** [comment]
@amitbatajoo 
Per the [README section Other Projects](https://github.com/box/box-java-sdk#other-projects) file, did you download the configuration file from your application's Configuration tab in the developer console and save it to /src/example/config/config.json?

I'm going to assume this resolves your issue, so I'll close it now.  But if that doesn't work for you, please re-open this issue and we'll go from there.  Thanks!
