### ISSUE TITLE
"Error parsing PKCS private key for Box Developer Edition" when using Java 11.0.7

### ISSUE THREAD

**Issue by bojanbt6** [box/box-java-sdk#800]
I am getting the following when running using the Box API with Java 11.0.7 (running the same code with Java 11.0.6 works fine).

Using Box API v2.41 (Same is happening on the latest one v2.47).
I am calling BoxApiConfig.getInstance().getConnection().authenticate()
and getting the following problem:

com.box.sdk.BoxAPIException: Error parsing PKCS private key for Box Developer Edition.
at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:515)
at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:450)
at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:431)
at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:320)
at com.sonyericsson.pfm.box.BoxApi$4.call(BoxApi.java:316)
at com.sonyericsson.pfm.box.BoxApi$4.call(BoxApi.java:1)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.bouncycastle.pkcs.PKCSException: unable to read encrypted data: 1.2.840.113549.1.5.13 not available: Service not registered with Provider BC: BC: SecretKeyFactory.PBKDF2WITHASCII -> org.bouncycastle.jcajce.provider.symmetric.PBEPBKDF2$PBKDF2with8BIT
  aliases: [PBKDF2WITH8BIT]

at org.bouncycastle.pkcs.PKCS8EncryptedPrivateKeyInfo.decryptPrivateKeyInfo(Unknown Source)
at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:504)
... 9 more
Caused by: org.bouncycastle.operator.OperatorCreationException: 1.2.840.113549.1.5.13 not available: Service not registered with Provider BC: BC: SecretKeyFactory.PBKDF2WITHASCII -> org.bouncycastle.jcajce.provider.symmetric.PBEPBKDF2$PBKDF2with8BIT
  aliases: [PBKDF2WITH8BIT]

	at org.bouncycastle.openssl.jcajce.JceOpenSSLPKCS8DecryptorProviderBuilder$1.get(Unknown Source)
	... 11 more
Caused by: java.security.NoSuchAlgorithmException: Service not registered with Provider BC: BC: SecretKeyFactory.PBKDF2WITHASCII -> org.bouncycastle.jcajce.provider.symmetric.PBEPBKDF2$PBKDF2with8BIT
  aliases: [PBKDF2WITH8BIT]

	at java.base/java.security.Provider$Service.newInstance(Provider.java:1785)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:135)
	at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:212)
	at org.bouncycastle.jcajce.util.NamedJcaJceHelper.createSecretKeyFactory(Unknown Source)
	at org.bouncycastle.openssl.jcajce.PEMUtilities.generateSecretKeyForPKCS5Scheme2(Unknown Source)
	... 12 more

**Comment by sujaygarlanka** [comment]
Something may have changed with the Java upgrade causing the decryption library to fail. We have not encountered this issue. If possible, I would try using the private key generated from our developer console. We have not had any reported issues with keys from there. Let us know if this works.

**Comment by bojanbt6** [comment]
Actually we are using an enterprise access token, so developer is a no go at the moment.
I will try to debug this further since it could be also connected to the BouncyCastle lib and some conflicts with Java.

**Comment by bojanbt6** [comment]
Updating to jose4j-0.7.0, bcprov-jdk15on-1.65 & bcpkix-jdk15on-1.65 instead of jose4j-0.6.4.jar, bcprov-jdk15on-1.54 & bcpkix-jdk15on-1.54 solves the problem.
I didn't had more time to dig deeper into the problem but this combination, at-least for now, seems to solve the problem.
