### ISSUE TITLE
 Couldn't connect to the Box API due to a network error in AccessAsAppUser.java.

### ISSUE THREAD

**Issue by amitbatajoo** [box/box-java-sdk#804]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported.
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

Please help me!
I tried to run the userAccessAsAppUser in the proxy setup network environment and I got this error message. 

First I complete all the api setup and also all the setting in box setup. 
Second I tried to run simple example runExample in same proxy network environment as   BoxAPIConnection as proxy setup. I was success to run the program.

But with same setting I tried to run userAccessAsAppUser, I go this error.

Any one can please help the solution. 

### Description of the Issue
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG
 (file:/C:/Users/clouduser/.gradle/caches/modules-2/files-2.1/org.bouncycastle/b
cprov-jdk15on/1.60/bd47ad3bd14b8e82595c7adaa143501e60842a84/bcprov-jdk15on-1.60.
jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.j
cajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect
ive access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" com.box.sdk.BoxAPIException: Couldn't connect to the
Box API due to a network error.
        at com.box.sdk.BoxAPIRequest.writeBody(BoxAPIRequest.java:566)
        at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:643)
        at com.box.sdk.BoxAPIRequest.sendWithoutRetry(BoxAPIRequest.java:326)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDevelope
rEditionAPIConnection.java:345)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTok
enCache(BoxDeveloperEditionAPIConnection.java:471)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(Box
DeveloperEditionAPIConnection.java:278)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppUserConnection(Box
DeveloperEditionAPIConnection.java:303)
        at com.box.sdk.example.AccessAsAppUser.main(AccessAsAppUser.java:43)
Caused by: java.net.UnknownHostException: api.box.com
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocke
tImpl.java:220)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:591)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:2
85)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)

        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)

        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.j
ava:265)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java
:372)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnecti
on.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(H
ttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Ht
tpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnecti
on.connect(AbstractDelegateHttpsURLConnection.java:179)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream
0(HttpURLConnection.java:1362)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream
(HttpURLConnection.java:1337)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutput
Stream(HttpsURLConnectionImpl.java:247)
        at com.box.sdk.BoxAPIRequest.writeBody(BoxAPIRequest.java:555)
        ... 7 more

> Task :runAccessAsAppUser FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runAccessAsAppUser'.
> Process 'command 'C:\Program Files\openjdk-12.0.2\jdk-12.0.2\bin\java.exe'' fi
nished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with
Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:comman
d_line_warnings

### Versions Used
Java SDK: 2.47.0
Java: openjdk-12.0.2

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

Thank you in advance!

**Comment by sujaygarlanka** [comment]
@amitbatajoo Try could be a proxy issue. The Java SDK does not support all proxy environments. I would try this first in a non proxy environment so we can determine whether proxy is in fact the issue.

**Comment by amitbatajoo** [comment]
@sujaygarlanka Thank you for your reply. I have tried the same program in non-proxy environment. It worked without error. But I tried it in  proxy setting environment. And I got the above error.

If there any suggestion for proxy setup to this program to run without error!

Thank you in advance!

**Comment by sujaygarlanka** [comment]
@amitbatajoo Currently, the SDK only supports basic Http and Https proxy. What proxy do you need support for?

**Comment by amitbatajoo** [comment]
@sujaygarlanka  Hello, thank you very much for your help and suggestion. Actually, I am able to solve this issue by the help of this innstruction.
https://github.com/box/box-java-sdk/issues/221

I am going to close this issue.

Again Thank you!
