### ISSUE TITLE
An exception occurred while instantiating a Java object. Error: com/eclipsesource/json/JsonValue.

### ISSUE THREAD

**Issue by felix822** [box/box-java-sdk#823]
When I try to run this code, I see the error message:
`rootFolder = createObject("java", "com.box.sdk.BoxFolder").getRootFolder(api);`

I cannot figure out where on the server to place the java files downloaded from minimal-json v0.9.1.

I am running Coldfusion 2016 and placed the jar files in the WEB-INF/lib folder, which seems to work. I tried to place the java files in there, as well as WEB-INF/classes. 

Stack Trace:
java.lang.NoClassDefFoundError: com/eclipsesource/json/JsonValue
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.privateGetPublicFields(Class.java:2614)
	at java.lang.Class.getFields(Class.java:1557)
	at coldfusion.runtime.java.ObjectHandler.Initialize(ObjectHandler.java:35)
	at coldfusion.runtime.java.ObjectHandler.<init>(ObjectHandler.java:30)
	at coldfusion.runtime.java.ReflectionCache.get(ReflectionCache.java:47)
	at coldfusion.runtime.java.JavaProxy.<init>(JavaProxy.java:35)
	at coldfusion.runtime.java.JavaProxyFactory.getProxy(JavaProxyFactory.java:121)
	at coldfusion.runtime.ProxyFactory.getProxy(ProxyFactory.java:68)
	at coldfusion.runtime.CFPage.createObjectProxy(CFPage.java:6674)
	at coldfusion.runtime.CFPage.CreateObject(CFPage.java:6637)
	at coldfusion.runtime.CFPage.CreateObject(CFPage.java:6571)
	at coldfusion.runtime.CFPage.CreateObject(CFPage.java:6497)
	at coldfusion.runtime.CFPage.CreateObject(CFPage.java:6438)
	at cfindex22ecfm47220339.runPage(/var/www/servers/mydev/root/htdocs/test/netsuite/index2.cfm:148)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:254)
	at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:743)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:573)
	at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65)
	at coldfusion.filter.IpFilter.invoke(IpFilter.java:45)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:505)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)
	at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:223)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:356)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:544)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.eclipsesource.json.JsonValue
	at coldfusion.bootstrap.BootstrapClassLoader.loadClass(BootstrapClassLoader.java:252)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 65 more

**Comment by sujaygarlanka** [comment]
@felix822 We recommend importing the SDK through maven. If you can't, this is a good [post](https://stackoverflow.com/questions/17381871/include-java-files-into-coldfusion) on how to import jar files into a Coldfusion project. Once you have included all the dependencies listed in the README [here](https://github.com/box/box-java-sdk#quickstart), I would run the sample project code found [here](https://github.com/box/box-java-sdk/blob/master/src/example/java/com/box/sdk/example/Main.java). I hope this helps. If you continue to have issues, feel free to re-open this.

**Comment by felix822** [comment]
Thanks @sujaygarlanka sujaygarlanka, that link helped.
