### ISSUE TITLE
upload file: getting "The API returned an error code [401] " error

### ISSUE THREAD

**Issue by felix822** [box/box-java-sdk#824]
After I connect to the API, I am trying to upload a .csv file. I keep getting this error message:
"The API returned an error code [401] "

Is there way to debug what exactly is going on? I know what 401 error means, but would like to know the details. Not sure what other info/details to post here.  Any input is appreciated. 

Stack trace:
`com.box.sdk.BoxAPIResponseException: The API returned an error code [401]
at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:92)
at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:679)
at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:381)
at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:348)
at com.box.sdk.BoxFolder.uploadFile(BoxFolder.java:552)
at com.box.sdk.BoxFolder.uploadFile(BoxFolder.java:457)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at coldfusion.runtime.StructBean.invoke(StructBean.java:508)
at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3316)
at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3224)
at cfindex22ecfm47220339.runPage(/var/www/servers/mydev/root/htdocs/test/netsuite/index2.cfm:158)
at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:254)
at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:743)
at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:573)
at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65)
at coldfusion.filter.IpFilter.invoke(IpFilter.java:45)
at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:505)
at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)
at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
at coldfusion.filter.PathFilter.invoke(PathFilter.java:153)
at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78)
at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
at coldfusion.CfmServlet.service(CfmServlet.java:223)
at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:356)
at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:544)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)`

**Comment by PJSimon** [comment]
Hi @felix822,

401 is usually token expired but it seems like you would have addressed that, so it might be something else. What authentication mechanism are you using? Also, did you remember to authorize the application for the Enterprise using the client-id in the admin console?

Thanks!

**Comment by felix822** [comment]
Hi @PJSimon, thanks for the quick reply. I am using the BoxAPIConnection authentication and passing in the boxConfig. I tried BoxDeveloperEditionAPIConnection a few different ways, but was getting an error. I'm not authenticating with a token; I am using the boxConfig (clientID, clientSecret, enterpriseID, jwtPreferences). Honestly, I am not really sure which method I'm supposed to be using to authenticate. Any input is greatly appreciated. 

I did click the Submit for Authorization button in the admin console, and was told by my client that they approved it, but I'm not really sure. I still see the button; should it change once authorized?

**Comment by carycheng** [comment]
Hey @felix822, there are definitely a few different authentication routes to choose from and it's easy to get them mixed up as we provide different paths for different use cases!

This article might be helpful in differentiating between the different authentication mechanisms we provide: https://developer.box.com/guides/authentication/select/. If you would look on the left side bar the two main ones I would say that fullfills the majority of use cases are: `OAuth 2.0 Auth` and `JWT Auth`. It seems to me that you are using the `JWT Auth` method currently.

However, to unblock you here some things you can provide us to help our team debug quicker, please include:

- Your code snippet that you are authing with(please don't forget to scrub any sensitive information such as client id or secret as well as any other id's)
- In your logs there should be a request id field that would be very helpful for us to use in tracking this down.
- Also I would double check with your admin that your app is indeed authorized in the admin console.

Lastly, if you haven't been to our Platform Community forum yet, I would strongly recommend it. We have members and a dedicated team that monitors that channel and they can provide great tips on circumventing your issue. You can find that forum [here](https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum).

**Comment by felix822** [comment]
Hi @carycheng, thank you for the link, I will check it out now. Which logs are you referring to that would have the request ID?

Here is my authentication code, minus the sensitive info (I am programming with Coldfusion, so this is cfscript):

`appConfig = {
  "boxAppSettings": {
    "clientID": "xxx",
    "clientSecret": "xxx",
    "appAuth": {
      "publicKeyID": "xxx",
      "privateKey": "xxx",
      "passphrase": "xxx"
    }
  },
  "enterpriseID": "xxx",
  "userID": "xxx"
};

EncryptionAlgorithm = createObject("java", "com.box.sdk.EncryptionAlgorithm");
jwtPreferences = createObject("java", "com.box.sdk.JWTEncryptionPreferences").init();
jwtPreferences.setPublicKeyID(appConfig.boxAppSettings.appAuth.publicKeyID);
jwtPreferences.setPrivateKeyPassword(appConfig.boxAppSettings.appAuth.passphrase);
jwtPreferences.setPrivateKey(appConfig.boxAppSettings.appAuth.privateKey);
jwtPreferences.setEncryptionAlgorithm(EncryptionAlgorithm.RSA_SHA_256);

boxConfig = createObject("java", "com.box.sdk.BoxConfig").init(appConfig.boxAppSettings.clientID, appConfig.boxAppSettings.clientSecret, appConfig.enterpriseID, jwtPreferences);
api = createObject("java", "com.box.sdk.BoxAPIConnection").init(boxConfig);

boxFolder = createObject("java", "com.box.sdk.BoxFolder").getRootFolder(api);`

Thanks again for your help; much appreciated.

**Comment by felix822** [comment]
Any ideas guys? I tried the forums, but have not had any replies yet.

**Comment by sujaygarlanka** [comment]
@felix822 Not sure what else is going wrong. I would try using simplifying the flow by using a developer token as shown [here](https://github.com/box/box-java-sdk/blob/master/doc/authentication.md#developer-token). Let us know if this works.

**Comment by felix822** [comment]
Thanks guys, I figured out the problem.
