### ISSUE TITLE
BoxZip create and download are returning a 401

### ISSUE THREAD

**Issue by llama-one** [box/box-java-sdk#845]
- [Y ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [Y ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ Y] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [Y ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I am using a code snippet like below to get a download URL using the new BoxZip item and it throws a 401 unauthorized exception - com.box.sdk.BoxAPIResponseException: The API returned an error code [401 | .06e21351cb691375825ca76a5ac93c4c5]

List<BoxZipItem> items = new ArrayList<>();
            BoxZipItem folder = new BoxZipItem("folder", folderId);
            items.add(folder);
            BoxZip zip = new BoxZip(api);
            BoxZipInfo zipInfo = zip.create("Awesome Zip File", items);

### Steps to Reproduce

See code snippet above.

### Expected Behavior
zipInfo.getDownloadURL() should return a URL to download the folder as a zip.

### Error Message, Including Stack Trace
com.box.sdk.BoxAPIResponseException: The API returned an error code [401 | .06e21351cb691375825ca76a5ac93c4c5]
	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:92)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:675)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:381)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:348)
	at com.box.sdk.BoxZip.create(BoxZip.java:56)
	at com.box.sdk.BoxZip.download(BoxZip.java:86)
	at com.box.sdk.BoxZip.download(BoxZip.java:72)

### Screenshots
N/A

### Versions Used
Java SDK: 2.50.1 & 2.50.0
Java: JDK11

**Comment by box-internship-take-home** [comment]
@llama-one A 401 means the token has expired. Are you using a developer token or JWT authentication?

**Comment by llama-one** [comment]
I'm using BoxDeveloperEditionAPIConnection object from the JAVA SDK which I believe uses JWT authentication under the hood. The token is not expired because I'm able to make all other protected API calls with the same token.

**Comment by sujaygarlanka** [comment]
@llama-one I believe this is because you cannot directly hit the url returned from `getDownloadURL()`. You must hit the download url with a client that has been authenticated. If you are trying to create and download a zip, then just using the download a zip method will work.

**Comment by llama-one** [comment]
I don't get to the point of getDownloanURL(). 
zip.create(...) throws the 401

**Comment by sujaygarlanka** [comment]
Create zip is public because some people may want to call it manually if they want to store download urls and download at a later time. What is your goal? Depending on that I can help you appropriately. Also, can you post the your code and remove any sensitive information like your client credentials and tokens.

**Comment by llama-one** [comment]
I just tested it some more. It works with a temporary developer token but not with JWT authentication.

**Working Code -**

```
        BoxAPIConnection api = new BoxAPIConnection(...);
        api.asUser(...);
        ArrayList<BoxZipItem> items = new ArrayList<BoxZipItem>();
        BoxZipItem folder = new BoxZipItem("folder", ...);
        items.add(folder);
        BoxZip zip = new BoxZip(api);
        BoxZipInfo zipInfo = zip.create("Awesome Zip File", items);
        System.out.println(zipInfo.getDownloadURL());
```

**Not Working Code**
```

        Reader reader = new FileReader(...);
        BoxConfig boxConfig = BoxConfig.readFrom(reader);
        BoxAPIConnection api = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig);
        api.asUser(...);
        ArrayList<BoxZipItem> items = new ArrayList<BoxZipItem>();
        BoxZipItem folder = new BoxZipItem("folder", ...);
        items.add(folder);
        BoxZip zip = new BoxZip(api);
        BoxZipInfo zipInfo = zip.create("Awesome Zip File", items);
        System.out.println(zipInfo.getDownloadURL());
```

The only difference is the authentication mechanism.

**Comment by llama-one** [comment]
Also woks with 

`BoxDeveloperEditionAPIConnection.getAppUserConnection("some-user-id", boxConfig)`

This looks like a bug. It shouldn't work / not work based on how the API connection is created.

**Comment by brookexu** [comment]
Did you enable the As User feature for your app? 
https://developer.box.com/guides/authentication/jwt/as-user/
