### ISSUE TITLE
アップロード中のメモリ不足

### ISSUE THREAD

**Issue by K-KODAIRA** [box/box-java-sdk#878]
We are copying files to BOX with our own tool using BOX API.

The following error will occur in this copy, so please tell me how to avoid this.

[2021/02/14 00:01:12.635][ERROR]][pool-289-thread-25] [0x1C000001] [operation is cloudtoolrt error.] Failed to connect box authentication. - [com.nec.jp.ias.migration.cloud.operation.FileUploadOperationThread#operationMain()]
com.nec.jp.ias.migration.cloud.util.CloudToolRTException: Failed to connect box authentication.
	at com.nec.jp.ias.migration.cloud.util.BoxErrorCheck.checkBoxErrorJson(BoxErrorCheck.java:96)
	at com.nec.jp.ias.migration.cloud.operation.FileUploadOperationThread.operationForNotExistFile(FileUploadOperationThread.java:205)
	at com.nec.jp.ias.migration.cloud.operation.FileUploadOperationThread.operationMain(FileUploadOperationThread.java:128)
	at com.nec.jp.ias.migration.cloud.operation.OperationThread.call(OperationThread.java:158)
	at com.nec.jp.ias.migration.cloud.operation.OperationThread.call(OperationThread.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

The above is the content of the error when the Java heap memory of the in-house tool is set to 3072GB.
When it is set to 2048GB, the same error or the following error will be mixed.

[2021/02/20 11:02:36.746][ERROR]][pool-133-thread-21] [0x1C000001] [operation is cloudtoolrt error.] Failed to connect box authentication. - [com.nec.jp.ias.migration.cloud.operation.FileUploadOperationThread#operationMain()]
com.nec.jp.ias.migration.cloud.util.CloudToolRTException: Failed to connect box authentication.
	at com.nec.jp.ias.migration.cloud.util.BoxErrorCheck.checkBoxErrorJson(BoxErrorCheck.java:96)
	at com.nec.jp.ias.migration.cloud.operation.FileUploadOperationThread.operationForNotExistFile(FileUploadOperationThread.java:205)
	at com.nec.jp.ias.migration.cloud.operation.FileUploadOperationThread.operationMain(FileUploadOperationThread.java:128)
	at com.nec.jp.ias.migration.cloud.operation.OperationThread.call(OperationThread.java:158)
	at com.nec.jp.ias.migration.cloud.operation.OperationThread.call(OperationThread.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
[2021/02/20 11:02:36.758][ERROR]][pool-133-thread-26] [0x00000000] out of memory error while uploading. - [com.nec.jp.ias.migration.cloud.operation.FileUploadOperationThread#operationForNotExistFile()]
java.lang.OutOfMemoryError: Java heap space
[2021/02/20 11:02:36.761][ERROR]][pool-133-thread-26] [0x1C000017] [operation is cloudtoolrt error.] Out of memory error while upload. - [com.nec.jp.ias.migration.cloud.operation.FileUploadOperationThread#operationMain()]
com.nec.jp.ias.migration.cloud.util.CloudToolRTException: Out of memory error while upload.
	at com.nec.jp.ias.migration.cloud.operation.FileUploadOperationThread.operationForNotExistFile(FileUploadOperationThread.java:241)
	at com.nec.jp.ias.migration.cloud.operation.FileUploadOperationThread.operationMain(FileUploadOperationThread.java:128)
	at com.nec.jp.ias.migration.cloud.operation.OperationThread.call(OperationThread.java:158)
	at com.nec.jp.ias.migration.cloud.operation.OperationThread.call(OperationThread.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by K-KODAIRA** [comment]
Hello swfree
Thank you for your reply.
Regarding confirmation,
     Java SDK BoxFolder.uploadLargeFile ()
Is calling.

**Comment by PJSimon** [comment]
Hi @K-KODAIRA ,

From the stack trace information you provided, we're not able to understand exactly how you're using the Box Java SDK.  In order to help you further on this issue, can you please provide some source code showing how you're using the Box Java SDK to authenticate with Box and how you're making the call to upload the file?

Also, is this issue only occurring when you try to upload a large file?  Or does it occur with small files, as well?

Thanks,

@PJSimon

**Comment by K-KODAIRA** [comment]
Hello PJSomon，
Sorry for the slow response.

Since the source code cannot be sent as it is,We will send you a sample.
-----
＜APIの作成＞ 
BoxAPIConnection api = new BoxAPIConnection(ユーザーのアクセストークン); 
api.setMaxRequestAttempts(1); 
api.setConnectTimeout(1時間); 
api.setReadTimeout(1時間); 
api.setProxy(プロキシサーバーの情報); 
api.setAutoRefresh(false); 
＜アップロード＞ 
BoxFolder toBoxFolder = new BoxFolder(api, アップロード先のフォルダーID); 
InputStream stream = new BufferedInputStream(new FileInputStream(アップロードするファイル)); 
Map<String,String> attributes = new HashMap<String, String>(); 
attributes.put("file_size", アップロードするファイルサイズ); 
attributes.put("content_modified_at", 日時); 
toBoxFolder.uploadLargeFile(stream, アップロードするファイル名, アップロードするファイルサイズ, attributes);
-----

How to authenticate with Box using Box Java SDK,
Have the refresh token obtained by authenticating on the screen
The access token is acquired / updated based on the refresh token.
This is used when creating the BoxAPIConnection object at the top of the above.

**Comment by PJSimon** [comment]
@K-KODAIRA 

Can you try calling `api.authenticate();` after `api.setProxy(プロキシサーバーの情報);` and see if that solves your issue?

Note that `setMaxRequestAttempts` is deprecated and `setMaxRetryAttempts` should be used.  (This is not related to your issue.)

**Comment by K-KODAIRA** [comment]
Hello PJSimon.
Thank you for your reply.

The answer is "pi.setProxy(プロキシサーバーの情報);", but will it help you avoid errors?
If there is a possibility of solving it, please tell us the background of this.

**Comment by PJSimon** [comment]
Hi @K-KODAIRA ,

I'm sorry, I don't understand your last message.

My recommendation is for you to change this code:
```
api.setProxy(プロキシサーバーの情報);
api.setAutoRefresh(false);
＜アップロード＞
BoxFolder toBoxFolder = new BoxFolder(api, アップロード先のフォルダーID);
```
... to this code:
```
api.setProxy(プロキシサーバーの情報);
api.setAutoRefresh(false);
api.authenticate();
＜アップロード＞
BoxFolder toBoxFolder = new BoxFolder(api, アップロード先のフォルダーID);
```

The reason is that api.authenticate(); needs to be called after you update the `api` object with the proxy information.  I'm suggesting you add this line of code before you use the `api` object again.

Did you try this?  Did it work?

When you reply, please "@ mention me" with @PJSimon so I can reply to your message as soon as possible!  :^)

**Comment by PJSimon** [comment]
Hi @K-KODAIRA ,

Is this issue resolved on your end?  If not, please feel free to re-open this ticket and we'll help you further!

Thanks,

Patrick

**Comment by K-KODAIRA** [comment]
Hello PJSimon.
I'm sorry that time has passed since I received your reply.

Again, can the next addition work around the memory error issue?
 api.authenticate();
