### ISSUE TITLE
BoxFileRequest is throwing com.box.sdk.BoxDeserializationException 

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#903]
- [X ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
The BoxFileRequest object is throwing BoxDeserializationException when trying to get the details of a File Request Link.

### Steps to Reproduce
    	BoxFileRequest fileRequest = new BoxFileRequest(api, "XXXX");
        BoxFileRequest.Info fileRequestInfo = fileRequest.getInfo();

### Expected Behavior
It should return a valid BoxFileRequest object. The REST API returns a valid response

### Error Message, Including Stack Trace
Exception in thread "main" com.box.sdk.BoxDeserializationException: Deserialization failed on: [ "field name": url | "field value": "/f/xxxxxxx" ]
	at com.box.sdk.BoxFileRequest$Info.parseJSONMember(BoxFileRequest.java:420)
	at com.box.sdk.BoxJSONObject.update(BoxJSONObject.java:200)
	at com.box.sdk.BoxJSONObject.<init>(BoxJSONObject.java:57)
	at com.box.sdk.BoxResource$Info.<init>(BoxResource.java:185)
	at com.box.sdk.BoxFileRequest$Info.<init>(BoxFileRequest.java:171)
	at com.box.sdk.BoxFileRequest.getInfo(BoxFileRequest.java:45)
	at fr.App.getGreeting(App.java:39)
	at fr.App.main(App.java:44)
Caused by: com.box.sdk.BoxAPIException: Couldn't parse url for file request
	at com.box.sdk.BoxFileRequest$Info.parseJSONMember(BoxFileRequest.java:416)
	... 7 more
Caused by: java.net.MalformedURLException: no protocol: /f/xxxxxxx
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at com.box.sdk.BoxFileRequest$Info.parseJSONMember(BoxFileRequest.java:414)
	... 7 more

### Screenshots
NA

### Versions Used
Java SDK: 2.54.0
Java: 1.8.0_201

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by rjainrohit** [comment]
@PJSimon @sujaygarlanka It seems the problem is in the REST API itself. The response is missing protocol and domain for the "url". Can this be fixed ASAP?

{
    "folder": {
        "id": "132637443689",
        "type": "folder",
        "name": "[External] Pinyon Legal Holds",
        "etag": "0",
        "sequence_id": "0"
    },
    "created_by": {
        "id": "1718605015",
        "type": "user",
        "name": "Rohit-NonProd",
        "login": "rjain@mgd.usda.gov"
    },
    "updated_by": {
        "id": "2234509301",
        "type": "user",
        "name": "Minru Liao",
        "login": "mliao03@usdagcc.mail.onmicrosoft.com"
    },
    "id": "671231635",
    "type": "file_request",
    "title": "Submit Legal Hold Forms",
    "description": "",
    "etag": "1626010004000",
    "is_email_required": false,
    "is_description_required": false,
    "url": "/f/72ff245d85274cae8a6c1d3951f9eac6",
    "created_at": "2021-03-01T14:29:41-08:00",
    "updated_at": "2021-07-11T06:26:44-07:00",
    "status": "active"
}

**Comment by mwwoda** [comment]
Hi @rjainrohit 

Sorry for the late response. We are currently investigating this issue. Will let you know if there are any updates on this.

Thanks,
@mwwoda
