### ISSUE TITLE
Box Sign BoxDeserializationException

### ISSUE THREAD

**Issue by kylefernandadams** [box/box-java-sdk#951]
### Description:
When looping through SignRequestInfo, I receive a deserialization error when trying to parse a date

###  Stack Trace:
```
com.box.sdk.BoxDeserializationException: Deserialization failed on: [ "field name": signers | "field value": [{"email":"kadams@boxdemo.com","role":"signer","is_in_person":false,"order":0,"verification_phone_number":null,"embed_url_external_user_id":null,"has_viewed_document":false,"signer_decision":{"type":"signed","finalized_at":"2021-12-01T20:56:40.180Z"},"inputs":[{"document_tag_id":null,"text_value":"Dec 1, 2021","checkbox_value":null,"date_value":"2021-12-01","type":"date","page_index":0},{"document_tag_id":null,"text_value":"","checkbox_value":null,"date_value":null,"type":"signature","page_index":0}],"embed_url":null}] ]
	at com.box.sdk.BoxSignRequest$Info.parseJSONMember(BoxSignRequest.java:637)
	at com.box.sdk.BoxJSONObject.update(BoxJSONObject.java:205)
	at com.box.sdk.BoxJSONObject.<init>(BoxJSONObject.java:56)
	at com.box.sdk.BoxResource$Info.<init>(BoxResource.java:189)
	at com.box.sdk.BoxSignRequest$Info.<init>(BoxSignRequest.java:381)
	at com.box.sdk.BoxSignRequest$1.factory(BoxSignRequest.java:186)
	at com.box.sdk.BoxSignRequest$1.factory(BoxSignRequest.java:181)
	at com.box.sdk.BoxResourceIterable$IteratorImpl.next(BoxResourceIterable.java:247)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at com.box.platform.sample.BoxSignExamples.getSignRequests(BoxSignExamples.java:26)
	at com.box.platform.sample.BoxSignExamples.main(BoxSignExamples.java:12)
Caused by: com.box.sdk.BoxDeserializationException: Deserialization failed on: [ "field name": inputs | "field value": [{"document_tag_id":null,"text_value":"Dec 1, 2021","checkbox_value":null,"date_value":"2021-12-01","type":"date","page_index":0},{"document_tag_id":null,"text_value":"","checkbox_value":null,"date_value":null,"type":"signature","page_index":0}] ]
	at com.box.sdk.BoxSignRequestSigner.parseJSONMember(BoxSignRequestSigner.java:243)
	at com.box.sdk.BoxJSONObject.update(BoxJSONObject.java:205)
	at com.box.sdk.BoxJSONObject.<init>(BoxJSONObject.java:56)
	at com.box.sdk.BoxSignRequestSigner.<init>(BoxSignRequestSigner.java:42)
	at com.box.sdk.BoxSignRequest$Info.parseJSONMember(BoxSignRequest.java:593)
	... 10 more
Caused by: com.box.sdk.BoxDeserializationException: Deserialization failed on: [ "field name": date_value | "field value": "2021-12-01" ]
	at com.box.sdk.BoxSignRequestSigner$BoxSignerInput.parseJSONMember(BoxSignRequestSigner.java:491)
	at com.box.sdk.BoxJSONObject.update(BoxJSONObject.java:205)
	at com.box.sdk.BoxJSONObject.<init>(BoxJSONObject.java:56)
	at com.box.sdk.BoxSignRequestSigner$BoxSignerInput.<init>(BoxSignRequestSigner.java:411)
	at com.box.sdk.BoxSignRequestSigner.parseJSONMember(BoxSignRequestSigner.java:235)
	... 14 more
Caused by: java.text.ParseException: Unparseable date: "2021-12-01"
	at java.base/java.text.DateFormat.parse(DateFormat.java:396)
	at com.box.sdk.BoxDateFormat.parse(BoxDateFormat.java:46)
	at com.box.sdk.BoxSignRequestSigner$BoxSignerInput.parseJSONMember(BoxSignRequestSigner.java:484)
	... 18 more
```

###  Sample Code:

```
package com.box.platform.sample;

import com.box.sdk.*;
import java.io.FileReader;
import java.util.logging.Logger;

public class BoxSignExamples {
    private static final Logger logger = Logger.getLogger(BoxSignExamples.class.getName());
    private static final int MAX_CACHE_ENTRIES = 100;
    public static void main(String[] args) {
        BoxSignExamples boxSignExamples = new BoxSignExamples();
        boxSignExamples.getSignRequests();
    }

    public void getSignRequests(){
        try{
            ClassLoader classLoader = getClass().getClassLoader();
            BoxConfig boxConfig = BoxConfig.readFrom(new FileReader(classLoader.getResource("box_config.json").getFile()));
            IAccessTokenCache accessTokenCache = new InMemoryLRUAccessTokenCache(MAX_CACHE_ENTRIES);
            BoxDeveloperEditionAPIConnection api = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig, accessTokenCache);
            BoxUser me = BoxUser.getCurrentUser(api);
            logger.info("Current User: " + me.getInfo().getLogin() + " name: " + me.getInfo().getName() + " id: " + me.getID());

            api.asUser("USER_ID_HERE");
            Iterable<BoxSignRequest.Info> signRequests = BoxSignRequest.getAll(api);
            signRequests.forEach(signRequestInfo -> {
                logger.info("Found sign request info with name: " + signRequestInfo.getName() + " and id: " + signRequestInfo.getName());
            });
            api.asSelf();
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }
}
```

**Comment by antusus** [comment]
Hi @kylefernandadams,

Thanks for submitting this Issue!
I can confirm that I can reproduce this issue. I'll let you know when there is a fix for that.

@antusus

**Comment by antusus** [comment]
Hi @kylefernandadams,

The release of version 3.0.0 contains the fix for this issue: https://github.com/box/box-java-sdk/releases/tag/v3.0.0

@antusus

**Comment by antusus** [comment]
Closing as fix was released. If this issue is still present please rach out to us.
